const UYGHUR_DATA = {
  alphabet: [
    { letter: "ئا", name: "Elif", latin: "a",   emoji: "🐴", example: "ئات",       exampleLatin: "at",         exampleEn: "horse" },
    { letter: "ئە", name: "E",    latin: "e",   emoji: "👓", example: "ئەينەك",    exampleLatin: "eynek",      exampleEn: "glasses" },
    { letter: "ب",  name: "Be",   latin: "b",   emoji: "🐟", example: "بېلىق",     exampleLatin: "béliq",      exampleEn: "fish" },
    { letter: "پ",  name: "Pe",   latin: "p",   emoji: "🐸", example: "پاقا",      exampleLatin: "paqa",       exampleEn: "frog" },
    { letter: "ت",  name: "Te",   latin: "t",   emoji: "🐰", example: "توشقان",    exampleLatin: "toshqan",    exampleEn: "rabbit" },
    { letter: "ج",  name: "Jim",  latin: "j",   emoji: "🥻", example: "جۇۋا",      exampleLatin: "juwa",       exampleEn: "robe/coat" },
    { letter: "چ",  name: "Che",  latin: "ch",  emoji: "🫖", example: "چەينەك",    exampleLatin: "cheynek",    exampleEn: "teapot" },
    { letter: "خ",  name: "Khe",  latin: "x",   emoji: "🐓", example: "خوراز",     exampleLatin: "xoraz",      exampleEn: "rooster" },
    { letter: "د",  name: "Dal",  latin: "d",   emoji: "🥁", example: "داپ",       exampleLatin: "dap",        exampleEn: "drum" },
    { letter: "ر",  name: "Re",   latin: "r",   emoji: "🪕", example: "راۋاپ",     exampleLatin: "rawap",      exampleEn: "rawap (lute)" },
    { letter: "ز",  name: "Ze",   latin: "z",   emoji: "⛓️", example: "زەنجىر",    exampleLatin: "zenjir",     exampleEn: "chain" },
    { letter: "ژ",  name: "Zhe",  latin: "zh",  emoji: "📰", example: "ژۇرنال",    exampleLatin: "zhurnal",    exampleEn: "magazine" },
    { letter: "س",  name: "Sin",  latin: "s",   emoji: "🕰️", example: "سائەت",     exampleLatin: "saet",       exampleEn: "clock/watch" },
    { letter: "ش",  name: "Shin", latin: "sh",  emoji: "🦁", example: "شىر",       exampleLatin: "shir",       exampleEn: "lion" },
    { letter: "غ",  name: "Ghe",  latin: "gh",  emoji: "🦢", example: "غاز",       exampleLatin: "ghaz",       exampleEn: "goose" },
    { letter: "ف",  name: "Fe",   latin: "f",   emoji: "⛲", example: "فونتان",    exampleLatin: "fontan",     exampleEn: "fountain" },
    { letter: "ق",  name: "Qaf",  latin: "q",   emoji: "🐑", example: "قوي",       exampleLatin: "qoy",        exampleEn: "sheep" },
    { letter: "ك",  name: "Ke",   latin: "k",   emoji: "🐄", example: "كالا",      exampleLatin: "kala",       exampleEn: "cattle/cow" },
    { letter: "گ",  name: "Ge",   latin: "g",   emoji: "🌸", example: "گۈل",       exampleLatin: "gül",        exampleEn: "flower" },
    { letter: "ڭ",  name: "Nge",  latin: "ng",  emoji: "🥜", example: "ياڭاق",     exampleLatin: "yangaq",     exampleEn: "walnut" },
    { letter: "ل",  name: "Lam",  latin: "l",   emoji: "💡", example: "لامپا",     exampleLatin: "lampa",      exampleEn: "lamp" },
    { letter: "م",  name: "Mim",  latin: "m",   emoji: "🐱", example: "مۈشۈك",     exampleLatin: "müshük",     exampleEn: "cat" },
    { letter: "ن",  name: "Nun",  latin: "n",   emoji: "🍞", example: "نان",       exampleLatin: "nan",        exampleEn: "bread" },
    { letter: "ھ",  name: "He",   latin: "h",   emoji: "🛒", example: "ھارۋا",     exampleLatin: "harwa",      exampleEn: "cart/wagon" },
    { letter: "و",  name: "Waw",  latin: "o/u", emoji: "🌾", example: "ئورغاق",    exampleLatin: "orghaq",     exampleEn: "sickle" },
    { letter: "ۇ",  name: "U",    latin: "u",   emoji: "🪺", example: "ئۇۋا",      exampleLatin: "uwa",        exampleEn: "nest" },
    { letter: "ۆ",  name: "Ö",    latin: "ö",   emoji: "🏠", example: "ئۆي",       exampleLatin: "öy",         exampleEn: "house" },
    { letter: "ۈ",  name: "Ü",    latin: "ü",   emoji: "🍇", example: "ئۈزۈم",     exampleLatin: "üzüm",       exampleEn: "grape" },
    { letter: "ۋ",  name: "We",   latin: "w/v", emoji: "🚲", example: "ۋېلىسىپىت", exampleLatin: "wélisipit",  exampleEn: "bicycle" },
    { letter: "ې",  name: "É",    latin: "é",   emoji: "🐻", example: "ئېيىق",     exampleLatin: "éyiq",       exampleEn: "bear" },
    { letter: "ى",  name: "Ye",   latin: "i/y", emoji: "🐶", example: "ئىت",       exampleLatin: "it",         exampleEn: "dog" },
    { letter: "ي",  name: "Yi",   latin: "y",   emoji: "🐯", example: "يولۋاس",    exampleLatin: "yolwas",     exampleEn: "tiger" },
  ],

  vocabulary: {
    greetings: [
      { uyghur: "سالام",          latin: "Salam",          english: "Hello",                   tip: "Like Arabic 'Salam'",  level: 1 },
      { uyghur: "ياخشى",          latin: "Yaxshi",         english: "Good / Fine",              tip: "Yax-shi",              level: 1 },
      { uyghur: "رەھمەت",         latin: "Rehmet",         english: "Thank you",                tip: "Reh-met",              level: 1 },
      { uyghur: "خوش",            latin: "Xosh",           english: "Goodbye",                  tip: "Khosh",                level: 1 },
      { uyghur: "ھەئە",           latin: "He'e",           english: "Yes",                      tip: "Heh-eh",               level: 1 },
      { uyghur: "ياق",            latin: "Yaq",            english: "No",                       tip: "Yak",                  level: 1 },
      { uyghur: "ياخشىمۇسىز",    latin: "Yaxshimusiz",    english: "How are you? (formal)",    tip: "Yax-shi-mu-siz",       level: 2 },
      { uyghur: "كەچۈرۈڭ",       latin: "Kechürüng",      english: "Sorry / Excuse me",        tip: "Ke-chü-rüng",          level: 2 },
      { uyghur: "خۇش كەپسىز",    latin: "Xush kepsiz",    english: "Welcome",                  tip: "Khush kep-siz",        level: 3 },
      { uyghur: "ئىسمىڭىز نېمە؟", latin: "Ismingiz néme?", english: "What is your name?",      tip: "Is-ming-iz né-me",     level: 3 },
    ],
    numbers: [
      { uyghur: "بىر",     latin: "Bir",     english: "1 - One",      tip: "Beer",        level: 1 },
      { uyghur: "ئىككى",  latin: "Ikki",    english: "2 - Two",      tip: "Ik-ki",       level: 1 },
      { uyghur: "ئۈچ",    latin: "Üch",     english: "3 - Three",    tip: "Üch",         level: 1 },
      { uyghur: "تۆت",    latin: "Töt",     english: "4 - Four",     tip: "Töt",         level: 1 },
      { uyghur: "بەش",    latin: "Besh",    english: "5 - Five",     tip: "Besh",        level: 1 },
      { uyghur: "ئالتە",  latin: "Alte",    english: "6 - Six",      tip: "Al-te",       level: 2 },
      { uyghur: "يەتتە",  latin: "Yette",   english: "7 - Seven",    tip: "Yet-te",      level: 2 },
      { uyghur: "سەككىز", latin: "Sekkiz",  english: "8 - Eight",    tip: "Sek-kiz",     level: 2 },
      { uyghur: "توققۇز", latin: "Toqquz",  english: "9 - Nine",     tip: "Toq-quz",     level: 2 },
      { uyghur: "ئون",    latin: "On",      english: "10 - Ten",     tip: "On",          level: 2 },
      { uyghur: "يىگىرمە",latin: "Yigirme", english: "20 - Twenty",  tip: "Yi-gir-me",   level: 3 },
      { uyghur: "يۈز",    latin: "Yüz",     english: "100 - Hundred",tip: "Yüz",         level: 3 },
    ],
    family: [
      { uyghur: "دادا",   latin: "Dada",   english: "Father",          tip: "Da-da",    level: 1 },
      { uyghur: "ئانا",   latin: "Ana",    english: "Mother",          tip: "A-na",     level: 1 },
      { uyghur: "ئاكا",   latin: "Aka",    english: "Older brother",   tip: "A-ka",     level: 2 },
      { uyghur: "ئاچە",   latin: "Ache",   english: "Older sister",    tip: "A-che",    level: 2 },
      { uyghur: "ئىنى",   latin: "Ini",    english: "Younger brother", tip: "I-ni",     level: 2 },
      { uyghur: "سىڭىل",  latin: "Singil", english: "Younger sister",  tip: "Sin-gil",  level: 2 },
      { uyghur: "بوۋى",   latin: "Buwi",   english: "Grandfather",     tip: "Bu-wi",    level: 3 },
      { uyghur: "موما",   latin: "Moma",   english: "Grandmother",     tip: "Mo-ma",    level: 3 },
      { uyghur: "ئوغۇل",  latin: "Oghul",  english: "Son",             tip: "Og-hul",   level: 3 },
      { uyghur: "قىز",    latin: "Qiz",    english: "Daughter / Girl", tip: "Qiz",      level: 3 },
    ],
    colors: [
      { uyghur: "قىزىل",     latin: "Qizil",    english: "Red",    tip: "Qi-zil",      level: 1 },
      { uyghur: "يېشىل",     latin: "Yéshil",   english: "Green",  tip: "Yé-shil",     level: 1 },
      { uyghur: "كۆك",       latin: "Kök",      english: "Blue",   tip: "Kök",         level: 1 },
      { uyghur: "سېرىق",     latin: "Sériq",    english: "Yellow", tip: "Sé-riq",      level: 2 },
      { uyghur: "ئاق",       latin: "Aq",       english: "White",  tip: "Aq",          level: 2 },
      { uyghur: "قارا",      latin: "Qara",     english: "Black",  tip: "Qa-ra",       level: 2 },
      { uyghur: "توق سېرىق", latin: "Toq sériq",english: "Orange", tip: "Toq sé-riq",  level: 3 },
      { uyghur: "بىنەپشە",   latin: "Binepshé", english: "Purple", tip: "Bi-nep-shé",  level: 3 },
    ],
    food: [
      { uyghur: "سۇ",      latin: "Su",       english: "Water",            tip: "Su",          level: 1 },
      { uyghur: "نان",     latin: "Nan",      english: "Bread / Naan",     tip: "Nan",         level: 1 },
      { uyghur: "چاي",     latin: "Chay",     english: "Tea",              tip: "Chay",        level: 2 },
      { uyghur: "ئالما",   latin: "Alma",     english: "Apple",            tip: "Al-ma",       level: 2 },
      { uyghur: "گۆش",    latin: "Gösh",     english: "Meat",             tip: "Gösh",        level: 2 },
      { uyghur: "ئۈزۈم",  latin: "Üzüm",     english: "Grape",            tip: "Ü-züm",       level: 3 },
      { uyghur: "پولو",    latin: "Polo",     english: "Rice dish (Pilaf)",tip: "Po-lo",       level: 3 },
      { uyghur: "تاۋاق",   latin: "Tawaq",    english: "Dish / Bowl",      tip: "Ta-waq",      level: 3 },
      { uyghur: "شىكەر",   latin: "Shiker",   english: "Sugar",            tip: "Shi-ker",     level: 4 },
      { uyghur: "يۇمۇرتقا",latin: "Yumurtqa", english: "Egg",              tip: "Yu-murt-qa",  level: 4 },
    ],
    animals: [
      { uyghur: "ئات",     latin: "At",     english: "Horse",    tip: "At",       level: 1 },
      { uyghur: "ئىت",     latin: "It",     english: "Dog",      tip: "It",       level: 1 },
      { uyghur: "مۈشۈك",  latin: "Müshük", english: "Cat",      tip: "Mü-shük",  level: 1 },
      { uyghur: "قوي",     latin: "Qoy",    english: "Sheep",    tip: "Qoy",      level: 2 },
      { uyghur: "توخۇ",    latin: "Toxu",   english: "Chicken",  tip: "To-xu",    level: 2 },
      { uyghur: "قۇش",    latin: "Qush",   english: "Bird",     tip: "Qush",     level: 2 },
      { uyghur: "بالىق",   latin: "Baliq",  english: "Fish",     tip: "Ba-liq",   level: 3 },
      { uyghur: "ئايىق",   latin: "Ayiq",   english: "Bear",     tip: "A-yiq",    level: 3 },
      { uyghur: "ئارسلان", latin: "Arslan", english: "Lion",     tip: "Ars-lan",  level: 4 },
      { uyghur: "پىل",     latin: "Pil",    english: "Elephant", tip: "Pil",      level: 4 },
    ],
    body: [
      { uyghur: "باش",    latin: "Bash",   english: "Head",      tip: "Bash",    level: 2 },
      { uyghur: "كۆز",    latin: "Köz",    english: "Eye",       tip: "Köz",     level: 2 },
      { uyghur: "قول",    latin: "Qol",    english: "Hand / Arm",tip: "Qol",     level: 2 },
      { uyghur: "ئاياق",  latin: "Ayaq",   english: "Foot / Leg",tip: "A-yaq",   level: 2 },
      { uyghur: "قۇلاق",  latin: "Qulaq",  english: "Ear",       tip: "Qu-laq",  level: 3 },
      { uyghur: "بۇرۇن",  latin: "Burun",  english: "Nose",      tip: "Bu-run",  level: 3 },
      { uyghur: "ئاغىز",  latin: "Aghiz",  english: "Mouth",     tip: "Ag-hiz",  level: 3 },
      { uyghur: "يۈرەك",  latin: "Yürek",  english: "Heart",     tip: "Yü-rek",  level: 4 },
    ],
    clothing: [
      { uyghur: "دوپپا",       latin: "Doppa",      english: "Uyghur cap (doppa)",  tip: "Dop-pa — the iconic square Uyghur hat",    level: 1 },
      { uyghur: "كۆيلەك",      latin: "Köylek",     english: "Dress / Shirt",        tip: "Köy-lek",                                  level: 1 },
      { uyghur: "شىم",         latin: "Shim",       english: "Trousers / Pants",     tip: "Shim",                                     level: 1 },
      { uyghur: "كىيىم",       latin: "Kiyim",      english: "Clothes / Garment",    tip: "Ki-yim — general word for clothing",        level: 1 },
      { uyghur: "پايپاق",      latin: "Paypaq",     english: "Socks / Stockings",    tip: "Pay-paq",                                  level: 2 },
      { uyghur: "ئەتەك",       latin: "Etek",       english: "Skirt",                tip: "E-tek",                                    level: 2 },
      { uyghur: "ئۆتۈك",       latin: "Ötük",       english: "Boots / Shoes",        tip: "Ö-tük",                                    level: 2 },
      { uyghur: "كامزۇل",      latin: "Kamzul",     english: "Vest / Waistcoat",     tip: "Kam-zul — worn over the shirt",            level: 3 },
      { uyghur: "تون",         latin: "Tun",        english: "Padded robe / Coat",   tip: "Tun — traditional Uyghur winter coat",     level: 3 },
      { uyghur: "ئورامال",     latin: "Oramal",     english: "Scarf / Handkerchief", tip: "O-ra-mal",                                 level: 4 },
    ],
    nature: [
      { uyghur: "كۈن",         latin: "Kün",        english: "Sun / Day",            tip: "Kün — also means 'day'",                   level: 1 },
      { uyghur: "ئاي",         latin: "Ay",         english: "Moon / Month",         tip: "Ay — also means 'month'",                  level: 1 },
      { uyghur: "يۇلتۇز",      latin: "Yultuz",     english: "Star",                 tip: "Yul-tuz",                                  level: 1 },
      { uyghur: "سۇ",          latin: "Su",         english: "Water",                tip: "Su",                                       level: 1 },
      { uyghur: "تاغ",         latin: "Tagh",       english: "Mountain",             tip: "Tagh",                                     level: 2 },
      { uyghur: "دەريا",       latin: "Derya",      english: "River",                tip: "Der-ya",                                   level: 2 },
      { uyghur: "ياغمۇر",      latin: "Yaghmur",    english: "Rain",                 tip: "Yagh-mur",                                 level: 2 },
      { uyghur: "قار",         latin: "Qar",        english: "Snow",                 tip: "Qar",                                      level: 2 },
      { uyghur: "شامال",       latin: "Shamal",     english: "Wind",                 tip: "Sha-mal",                                  level: 3 },
      { uyghur: "ئورمان",      latin: "Orman",      english: "Forest / Woods",       tip: "Or-man",                                   level: 3 },
      { uyghur: "كۆل",         latin: "Köl",        english: "Lake",                 tip: "Köl",                                      level: 3 },
      { uyghur: "ئاسمان",      latin: "Asman",      english: "Sky",                  tip: "As-man",                                   level: 3 },
      { uyghur: "يەر",         latin: "Yer",        english: "Earth / Ground",       tip: "Yer",                                      level: 4 },
      { uyghur: "چۆل",         latin: "Chöl",       english: "Desert / Steppe",      tip: "Chöl — Central Asia's vast grasslands",    level: 4 },
    ],
    school: [
      { uyghur: "مەكتەپ",      latin: "Mektep",     english: "School",               tip: "Mek-tep",                                  level: 1 },
      { uyghur: "كىتاب",       latin: "Kitab",      english: "Book",                 tip: "Ki-tab",                                   level: 1 },
      { uyghur: "قەلەم",       latin: "Qelem",      english: "Pen / Pencil",         tip: "Qe-lem",                                   level: 1 },
      { uyghur: "خالتا",       latin: "Xalta",      english: "Bag / Backpack",       tip: "Xal-ta",                                   level: 1 },
      { uyghur: "ئوقۇتقۇچى",  latin: "Oqutquchi",  english: "Teacher",              tip: "O-qut-qu-chi",                             level: 2 },
      { uyghur: "ئوقۇغۇچى",   latin: "Oqughuchi",  english: "Student",              tip: "O-qugh-u-chi",                             level: 2 },
      { uyghur: "دەرس",        latin: "Ders",       english: "Lesson / Class",       tip: "Ders",                                     level: 2 },
      { uyghur: "تاختا",       latin: "Taxta",      english: "Blackboard",           tip: "Tax-ta",                                   level: 2 },
      { uyghur: "ئىمتىھان",    latin: "Imtihan",    english: "Exam / Test",          tip: "Im-ti-han — from Arabic",                  level: 3 },
      { uyghur: "مەكتەپخانا", latin: "Mektepxana", english: "Classroom",            tip: "Mek-tep-xa-na",                            level: 3 },
      { uyghur: "ئوقۇش",       latin: "Oqush",      english: "Reading / Study",      tip: "O-qush",                                   level: 3 },
      { uyghur: "يازماق",      latin: "Yazmaq",     english: "To write",             tip: "Yaz-maq",                                  level: 4 },
    ],
  },

  phrases: [
    { uyghur: "مەن سىزنى سۆيىمەن",              latin: "Men sizni söyimen",              english: "I love you" },
    { uyghur: "بۇ نېمە؟",                        latin: "Bu néme?",                       english: "What is this?" },
    { uyghur: "قەيەردە؟",                        latin: "Qeyerde?",                       english: "Where is it?" },
    { uyghur: "قانچە پۇل؟",                      latin: "Qanche pul?",                    english: "How much does it cost?" },
    { uyghur: "مەن ئۇيغۇر تىلىنى ئۆگىنىۋاتىمەن",latin: "Men uyghur tilini öginiwatimen", english: "I am learning Uyghur" },
    { uyghur: "ئۇيغۇرچە سۆزلەڭ",               latin: "Uyghurche sözleng",              english: "Speak Uyghur" },
    { uyghur: "ماڭا ياردەم قىلامسىز؟",           latin: "Manga yardem qilamsiz?",         english: "Can you help me?" },
    { uyghur: "چۈشەنمىدىم",                      latin: "Chüshenmidim",                   english: "I didn't understand" },
    { uyghur: "تېخىمۇ ئاستە ئېيتىڭ",            latin: "Téximu aste éyting",             english: "Please speak more slowly" },
  ],

  levels: [
    { level: 1, name: "Beginner",     uyghur: "يېڭى ئۆگەنگۈچى", emoji: "🌱", xpRequired: 0,   color: "#10B981", desc: "Basic words every learner needs" },
    { level: 2, name: "Elementary",   uyghur: "ئاساسىي",         emoji: "📗", xpRequired: 100, color: "#3B82F6", desc: "Build on the basics" },
    { level: 3, name: "Intermediate", uyghur: "ئوتتۇرا",         emoji: "⭐", xpRequired: 300, color: "#F59E0B", desc: "Expand your vocabulary" },
    { level: 4, name: "Advanced",     uyghur: "ئىلغار",          emoji: "🏆", xpRequired: 600, color: "#8B5CF6", desc: "Master all categories" },
  ]
};
