const UYGHUR_DATA = {
  alphabet: [
    { letter: "ئا", name: "Elif", latin: "a", example: "ئالما", exampleLatin: "alma", exampleEn: "apple" },
    { letter: "ئە", name: "E", latin: "e", example: "ئەر", exampleLatin: "er", exampleEn: "husband/man" },
    { letter: "ب", name: "Be", latin: "b", example: "بال", exampleLatin: "bal", exampleEn: "honey" },
    { letter: "پ", name: "Pe", latin: "p", example: "پول", exampleLatin: "pul", exampleEn: "money" },
    { letter: "ت", name: "Te", latin: "t", example: "تاش", exampleLatin: "tash", exampleEn: "stone" },
    { letter: "ج", name: "Je", latin: "j", example: "جاي", exampleLatin: "jay", exampleEn: "place" },
    { letter: "چ", name: "Che", latin: "ch", example: "چاي", exampleLatin: "chay", exampleEn: "tea" },
    { letter: "خ", name: "Khe", latin: "x", example: "خات", exampleLatin: "xat", exampleEn: "letter/mail" },
    { letter: "د", name: "Dal", latin: "d", example: "دەرياۋ", exampleLatin: "deryaw", exampleEn: "river" },
    { letter: "ر", name: "Re", latin: "r", example: "رەڭ", exampleLatin: "reng", exampleEn: "color" },
    { letter: "ز", name: "Ze", latin: "z", example: "زەمىن", exampleLatin: "zemin", exampleEn: "land/earth" },
    { letter: "ژ", name: "Zhe", latin: "zh", example: "ژۇرنال", exampleLatin: "zhurnal", exampleEn: "magazine" },
    { letter: "س", name: "Sin", latin: "s", example: "سۇ", exampleLatin: "su", exampleEn: "water" },
    { letter: "ش", name: "Shin", latin: "sh", example: "شام", exampleLatin: "sham", exampleEn: "dinner/evening" },
    { letter: "غ", name: "Ghayn", latin: "gh", example: "غوز", exampleLatin: "ghuz", exampleEn: "walnut" },
    { letter: "ف", name: "Fe", latin: "f", example: "فىل", exampleLatin: "fil", exampleEn: "elephant" },
    { letter: "ق", name: "Qaf", latin: "q", example: "قوي", exampleLatin: "qoy", exampleEn: "sheep" },
    { letter: "ك", name: "Kef", latin: "k", example: "كىتاب", exampleLatin: "kitab", exampleEn: "book" },
    { letter: "گ", name: "Gef", latin: "g", example: "گۈل", exampleLatin: "gül", exampleEn: "flower" },
    { letter: "ڭ", name: "Nge", latin: "ng", example: "ئاڭ", exampleLatin: "ang", exampleEn: "sound/sense" },
    { letter: "ل", name: "Lam", latin: "l", example: "لالە", exampleLatin: "lale", exampleEn: "tulip" },
    { letter: "م", name: "Mim", latin: "m", example: "مەيدان", exampleLatin: "meydan", exampleEn: "square/field" },
    { letter: "ن", name: "Nun", latin: "n", example: "نان", exampleLatin: "nan", exampleEn: "bread" },
    { letter: "ھ", name: "He", latin: "h", example: "ھەم", exampleLatin: "hem", exampleEn: "also/and" },
    { letter: "و", name: "Waw", latin: "o/u", example: "ئوت", exampleLatin: "ot", exampleEn: "fire/grass" },
    { letter: "ۇ", name: "U", latin: "u", example: "ئۇل", exampleLatin: "ul", exampleEn: "son" },
    { letter: "ۆ", name: "Ö", latin: "ö", example: "ئۆي", exampleLatin: "öy", exampleEn: "house" },
    { letter: "ۈ", name: "Ü", latin: "ü", example: "ئۈزۈم", exampleLatin: "üzüm", exampleEn: "grape" },
    { letter: "ۋ", name: "We", latin: "w/v", example: "ۋاق", exampleLatin: "waq", exampleEn: "time/moment" },
    { letter: "ې", name: "É", latin: "é", example: "ئېغىز", exampleLatin: "éghiz", exampleEn: "mouth" },
    { letter: "ى", name: "Ye", latin: "i/y", example: "يىل", exampleLatin: "yil", exampleEn: "year" },
    { letter: "ي", name: "Yi", latin: "y", example: "يول", exampleLatin: "yol", exampleEn: "road/way" },
  ],

  vocabulary: {
    greetings: [
      { uyghur: "سالام", latin: "Salam", english: "Hello", tip: "Like Arabic 'Salam'" },
      { uyghur: "ياخشىمۇسىز", latin: "Yaxshimusiz", english: "How are you? (formal)", tip: "Yax-shi-mu-siz" },
      { uyghur: "ياخشى", latin: "Yaxshi", english: "Good / Fine", tip: "Yax-shi" },
      { uyghur: "رەھمەت", latin: "Rehmet", english: "Thank you", tip: "Reh-met" },
      { uyghur: "خوش", latin: "Xosh", english: "Goodbye", tip: "Khosh" },
      { uyghur: "ھەئە", latin: "Hee'e", english: "Yes", tip: "Heh-eh" },
      { uyghur: "ياق", latin: "Yaq", english: "No", tip: "Yak" },
      { uyghur: "كەچۈرۈڭ", latin: "Kechürüng", english: "Sorry / Excuse me", tip: "Ke-chü-rüng" },
      { uyghur: "خۇش كەپسىز", latin: "Xush kepsiz", english: "Welcome", tip: "Khush kep-siz" },
      { uyghur: "ئىسمىڭىز نېمە؟", latin: "Ismingiz néme?", english: "What is your name?", tip: "Is-ming-iz né-me" },
    ],
    numbers: [
      { uyghur: "بىر", latin: "Bir", english: "1 - One", tip: "Beer" },
      { uyghur: "ئىككى", latin: "Ikki", english: "2 - Two", tip: "Ik-ki" },
      { uyghur: "ئۈچ", latin: "Üch", english: "3 - Three", tip: "Üch (like 'uch')" },
      { uyghur: "تۆت", latin: "Töt", english: "4 - Four", tip: "Töt" },
      { uyghur: "بەش", latin: "Besh", english: "5 - Five", tip: "Besh" },
      { uyghur: "ئالتە", latin: "Alte", english: "6 - Six", tip: "Al-te" },
      { uyghur: "يەتتە", latin: "Yette", english: "7 - Seven", tip: "Yet-te" },
      { uyghur: "سەككىز", latin: "Sekkiz", english: "8 - Eight", tip: "Sek-kiz" },
      { uyghur: "توققۇز", latin: "Toqquz", english: "9 - Nine", tip: "Toq-quz" },
      { uyghur: "ئون", latin: "On", english: "10 - Ten", tip: "On" },
      { uyghur: "يىگىرمە", latin: "Yigirme", english: "20 - Twenty", tip: "Yi-gir-me" },
      { uyghur: "يۈز", latin: "Yüz", english: "100 - Hundred", tip: "Yüz" },
    ],
    family: [
      { uyghur: "دادا", latin: "Dada", english: "Father", tip: "Da-da" },
      { uyghur: "ئانا", latin: "Ana", english: "Mother", tip: "A-na" },
      { uyghur: "ئاكا", latin: "Aka", english: "Older brother", tip: "A-ka" },
      { uyghur: "ئاچە", latin: "Ache", english: "Older sister", tip: "A-che" },
      { uyghur: "ئىنى", latin: "Ini", english: "Younger brother", tip: "I-ni" },
      { uyghur: "سىڭىل", latin: "Singil", english: "Younger sister", tip: "Sin-gil" },
      { uyghur: "بوۋا", latin: "Bowa", english: "Grandfather", tip: "Bo-wa" },
      { uyghur: "مومى", latin: "Momi", english: "Grandmother", tip: "Mo-mi" },
      { uyghur: "ئوغۇل", latin: "Oghul", english: "Son", tip: "Og-hul" },
      { uyghur: "قىز", latin: "Qiz", english: "Daughter / Girl", tip: "Qiz" },
    ],
    colors: [
      { uyghur: "قىزىل", latin: "Qizil", english: "Red", tip: "Qi-zil" },
      { uyghur: "يېشىل", latin: "Yéshil", english: "Green", tip: "Yé-shil" },
      { uyghur: "كۆك", latin: "Kök", english: "Blue / Sky blue", tip: "Kök" },
      { uyghur: "سېرىق", latin: "Sériq", english: "Yellow", tip: "Sé-riq" },
      { uyghur: "ئاق", latin: "Aq", english: "White", tip: "Aq" },
      { uyghur: "قارا", latin: "Qara", english: "Black", tip: "Qa-ra" },
      { uyghur: "توق سېرىق", latin: "Toq sériq", english: "Orange", tip: "Toq sé-riq" },
      { uyghur: "بىنەپشە", latin: "Binepshé", english: "Purple", tip: "Bi-nep-shé" },
    ],
    food: [
      { uyghur: "نان", latin: "Nan", english: "Bread / Naan", tip: "Nan" },
      { uyghur: "سۇ", latin: "Su", english: "Water", tip: "Su" },
      { uyghur: "گۆش", latin: "Gösh", english: "Meat", tip: "Gösh" },
      { uyghur: "پولو", latin: "Polo", english: "Rice dish (Pilaf)", tip: "Po-lo" },
      { uyghur: "چاي", latin: "Chay", english: "Tea", tip: "Chay" },
      { uyghur: "ئالما", latin: "Alma", english: "Apple", tip: "Al-ma" },
      { uyghur: "ئۈزۈم", latin: "Üzüm", english: "Grape", tip: "Ü-züm" },
      { uyghur: "تاۋاق", latin: "Tawaq", english: "Dish / Bowl", tip: "Ta-waq" },
      { uyghur: "شىكەر", latin: "Shiker", english: "Sugar", tip: "Shi-ker" },
      { uyghur: "يۇمۇرتقا", latin: "Yumurtqa", english: "Egg", tip: "Yu-murt-qa" },
    ],
    animals: [
      { uyghur: "ئات", latin: "At", english: "Horse", tip: "At" },
      { uyghur: "ئىت", latin: "It", english: "Dog", tip: "It" },
      { uyghur: "مۈشۈك", latin: "Müshük", english: "Cat", tip: "Mü-shük" },
      { uyghur: "قوي", latin: "Qoy", english: "Sheep", tip: "Qoy" },
      { uyghur: "توخۇ", latin: "Toxu", english: "Chicken", tip: "To-xu" },
      { uyghur: "بالىق", latin: "Baliq", english: "Fish", tip: "Ba-liq" },
      { uyghur: "ئارسلان", latin: "Arslan", english: "Lion", tip: "Ars-lan" },
      { uyghur: "ئايىق", latin: "Ayiq", english: "Bear", tip: "A-yiq" },
      { uyghur: "قۇش", latin: "Qush", english: "Bird", tip: "Qush" },
      { uyghur: "پىل", latin: "Pil", english: "Elephant", tip: "Pil" },
    ],
    body: [
      { uyghur: "باش", latin: "Bash", english: "Head", tip: "Bash" },
      { uyghur: "كۆز", latin: "Köz", english: "Eye", tip: "Köz" },
      { uyghur: "قۇلاق", latin: "Qulaq", english: "Ear", tip: "Qu-laq" },
      { uyghur: "بۇرۇن", latin: "Burun", english: "Nose", tip: "Bu-run" },
      { uyghur: "ئاغىز", latin: "Aghiz", english: "Mouth", tip: "Ag-hiz" },
      { uyghur: "قول", latin: "Qol", english: "Hand / Arm", tip: "Qol" },
      { uyghur: "ئاياق", latin: "Ayaq", english: "Foot / Leg", tip: "A-yaq" },
      { uyghur: "يۈرەك", latin: "Yürek", english: "Heart", tip: "Yü-rek" },
    ],
  },

  phrases: [
    { uyghur: "مەن سىزنى سۆيىمەن", latin: "Men sizni söyimen", english: "I love you" },
    { uyghur: "بۇ نېمە؟", latin: "Bu néme?", english: "What is this?" },
    { uyghur: "قەيەردە؟", latin: "Qeyerde?", english: "Where is it?" },
    { uyghur: "قانچە پۇل؟", latin: "Qanche pul?", english: "How much does it cost?" },
    { uyghur: "مەن ئۇيغۇر تىلىنى ئۆگىنىۋاتىمەن", latin: "Men uyghur tilini öginiwatimen", english: "I am learning Uyghur" },
    { uyghur: "ئۇيغۇرچە سۆزلەڭ", latin: "Uyghurche sözleng", english: "Speak Uyghur" },
    { uyghur: "ياردەم قىلامسىز؟", latin: "Yardem qilamsiz?", english: "Can you help me?" },
    { uyghur: "چۈشەنمىدىم", latin: "Chüshenmidim", english: "I didn't understand" },
    { uyghur: "تېخىمۇ ئاستە ئېيتىڭ", latin: "Téximu aste éyting", english: "Please speak more slowly" },
  ]
};
