const UYGHUR_DATA = {
  alphabet: [
    { letter: "ئا", name: "A",   latin: "a",  ipa: "ɑ",   type: "vowel",     howToRead: "a as in father",                              emoji: "🐴", example: "ئات",        exampleLatin: "at",        exampleEn: "horse" },
    { letter: "ئە", name: "E",   latin: "e",  ipa: "æ/ɛ", type: "vowel",     howToRead: "e as in bed / apple",                         emoji: "👓", example: "ئەينەك",     exampleLatin: "eynek",     exampleEn: "glasses" },
    { letter: "ب",  name: "Be",  latin: "b",  ipa: "b",   type: "consonant", howToRead: "b as in boy",                                 emoji: "🐟", example: "بېلىق",     exampleLatin: "béliq",     exampleEn: "fish" },
    { letter: "پ",  name: "Pe",  latin: "p",  ipa: "p",   type: "consonant", howToRead: "p as in pen",                                 emoji: "🐸", example: "پاقا",      exampleLatin: "paqa",      exampleEn: "frog" },
    { letter: "ت",  name: "Te",  latin: "t",  ipa: "t",   type: "consonant", howToRead: "t as in ten",                                 emoji: "🐰", example: "توشقان",    exampleLatin: "toshqan",   exampleEn: "rabbit" },
    { letter: "ج",  name: "Je",  latin: "j",  ipa: "dʒ",  type: "consonant", howToRead: "j as in jam",                                 emoji: "🚿", example: "جار",       exampleLatin: "jar",       exampleEn: "announcement" },
    { letter: "چ",  name: "Che", latin: "ch", ipa: "tʃ",  type: "consonant", howToRead: "ch as in chair",                              emoji: "🫖", example: "چەينەك",    exampleLatin: "cheynek",   exampleEn: "teapot" },
    { letter: "خ",  name: "Xe",  latin: "x",  ipa: "χ",   type: "consonant", howToRead: "rough kh sound, like German Bach",             emoji: "🐓", example: "خوراز",     exampleLatin: "xoraz",     exampleEn: "rooster" },
    { letter: "د",  name: "De",  latin: "d",  ipa: "d",   type: "consonant", howToRead: "d as in day",                                 emoji: "🥁", example: "داپ",       exampleLatin: "dap",       exampleEn: "drum" },
    { letter: "ر",  name: "Re",  latin: "r",  ipa: "r",   type: "consonant", howToRead: "rolled / trilled r",                          emoji: "🪕", example: "راۋاپ",     exampleLatin: "rawap",     exampleEn: "rawap (lute)" },
    { letter: "ز",  name: "Ze",  latin: "z",  ipa: "z",   type: "consonant", howToRead: "z as in zoo",                                 emoji: "⛓️", example: "زەنجىر",    exampleLatin: "zenjir",    exampleEn: "chain" },
    { letter: "ژ",  name: "Zhe", latin: "zh", ipa: "ʒ",   type: "consonant", howToRead: "s as in measure",                             emoji: "📰", example: "ژۇرنال",    exampleLatin: "zhurnal",   exampleEn: "magazine" },
    { letter: "س",  name: "Se",  latin: "s",  ipa: "s",   type: "consonant", howToRead: "s as in sun",                                 emoji: "🕰️", example: "سائەت",     exampleLatin: "saet",      exampleEn: "clock/watch" },
    { letter: "ش",  name: "She", latin: "sh", ipa: "ʃ",   type: "consonant", howToRead: "sh as in shoe",                               emoji: "🦁", example: "شىر",       exampleLatin: "shir",      exampleEn: "lion" },
    { letter: "غ",  name: "Ghe", latin: "gh", ipa: "ʁ/ɣ", type: "consonant", howToRead: "voiced deep gh sound",                        emoji: "🦢", example: "غاز",       exampleLatin: "ghaz",      exampleEn: "goose" },
    { letter: "ف",  name: "Fe",  latin: "f",  ipa: "f",   type: "consonant", howToRead: "f as in fish",                                emoji: "⛲", example: "فونتان",    exampleLatin: "fontan",    exampleEn: "fountain" },
    { letter: "ق",  name: "Qe",  latin: "q",  ipa: "q",   type: "consonant", howToRead: "deep back-k sound",                           emoji: "🐑", example: "قوي",       exampleLatin: "qoy",       exampleEn: "sheep" },
    { letter: "ك",  name: "Ke",  latin: "k",  ipa: "k",   type: "consonant", howToRead: "k as in kite",                                emoji: "🐄", example: "كالا",      exampleLatin: "kala",      exampleEn: "cattle/cow" },
    { letter: "گ",  name: "Ge",  latin: "g",  ipa: "g",   type: "consonant", howToRead: "g as in go",                                  emoji: "🌸", example: "گۈل",       exampleLatin: "gül",       exampleEn: "flower" },
    { letter: "ڭ",  name: "Nge", latin: "ng", ipa: "ŋ",   type: "consonant", howToRead: "ng as in song",                               emoji: "🥜", example: "ياڭاق",     exampleLatin: "yangaq",    exampleEn: "walnut" },
    { letter: "ل",  name: "Le",  latin: "l",  ipa: "l",   type: "consonant", howToRead: "l as in lamp",                                emoji: "💡", example: "لامپا",     exampleLatin: "lampa",     exampleEn: "lamp" },
    { letter: "م",  name: "Me",  latin: "m",  ipa: "m",   type: "consonant", howToRead: "m as in moon",                                emoji: "🐱", example: "مۈشۈك",     exampleLatin: "müshük",    exampleEn: "cat" },
    { letter: "ن",  name: "Ne",  latin: "n",  ipa: "n",   type: "consonant", howToRead: "n as in nose",                                emoji: "🍞", example: "نان",       exampleLatin: "nan",       exampleEn: "bread" },
    { letter: "ھ",  name: "He",  latin: "h",  ipa: "h",   type: "consonant", howToRead: "h as in hat",                                 emoji: "🛒", example: "ھارۋا",     exampleLatin: "harwa",     exampleEn: "cart/wagon" },
    { letter: "ئو", name: "O",   latin: "o",  ipa: "o",   type: "vowel",     howToRead: "o as in more (rounded)",                      emoji: "🌾", example: "ئورغاق",    exampleLatin: "orghaq",    exampleEn: "sickle" },
    { letter: "ئۇ", name: "U",   latin: "u",  ipa: "u",   type: "vowel",     howToRead: "u as in rule / moon",                         emoji: "🍇", example: "ئۇيا",      exampleLatin: "uya",       exampleEn: "nest" },
    { letter: "ئۆ", name: "Ö",   latin: "ö",  ipa: "ø",   type: "vowel",     howToRead: "rounded e sound, like German / French ö",     emoji: "👢", example: "ئۆتۈك",     exampleLatin: "ötük",      exampleEn: "boots" },
    { letter: "ئۈ", name: "Ü",   latin: "ü",  ipa: "y",   type: "vowel",     howToRead: "rounded ee sound, like German ü",             emoji: "🍇", example: "ئۈزۈم",     exampleLatin: "üzüm",      exampleEn: "grape" },
    { letter: "ۋ",  name: "We",  latin: "w",  ipa: "w/v", type: "consonant", howToRead: "w as in water (sometimes close to v)",        emoji: "🚲", example: "ۋېلىسىپىت", exampleLatin: "wélisipit", exampleEn: "bicycle" },
    { letter: "ې",  name: "É",   latin: "é",  ipa: "e",   type: "vowel",     howToRead: "ay/e sound, like hey without strong y",       emoji: "🐻", example: "ئېيىق",     exampleLatin: "éyiq",      exampleEn: "bear" },
    { letter: "ى",  name: "I",   latin: "i",  ipa: "i/ɪ", type: "vowel",     howToRead: "i/ee sound as in machine or sit",             emoji: "🐶", example: "ئىت",       exampleLatin: "it",        exampleEn: "dog" },
    { letter: "ي",  name: "Ye",  latin: "y",  ipa: "j",   type: "consonant", howToRead: "y as in yes",                                 emoji: "🐯", example: "يولۋاس",    exampleLatin: "yolwas",    exampleEn: "tiger" },
  ],

  vocabulary: {
    greetings: [
      { uyghur: "سالام",           latin: "Salam",           english: "Hello",                    tip: "Like Arabic 'Salam'",         level: 1 },
      { uyghur: "ياخشى",           latin: "Yaxshi",          english: "Good / Fine",               tip: "Yax-shi",                     level: 1 },
      { uyghur: "رەھمەت",          latin: "Rehmet",          english: "Thank you",                 tip: "Reh-met",                     level: 1 },
      { uyghur: "خوش",             latin: "Xosh",            english: "Goodbye",                   tip: "Khosh",                       level: 1 },
      { uyghur: "ھەئە",            latin: "He'e",            english: "Yes",                       tip: "Heh-eh",                      level: 1 },
      { uyghur: "ياق",             latin: "Yaq",             english: "No",                        tip: "Yak",                         level: 1 },
      { uyghur: "دوست",            latin: "Dost",            english: "Friend",                    tip: "Dost — from Persian",         level: 1 },
      { uyghur: "بايرام",          latin: "Bayram",          english: "Holiday / Festival",        tip: "Bay-ram",                     level: 2 },
      { uyghur: "ياخشىمۇسىز",     latin: "Yaxshimusiz",     english: "How are you? (formal)",     tip: "Yax-shi-mu-siz",              level: 2 },
      { uyghur: "كەچۈرۈڭ",        latin: "Kechürüng",       english: "Sorry / Excuse me",         tip: "Ke-chü-rüng",                 level: 2 },
      { uyghur: "مىھمان",          latin: "Mihman",          english: "Guest",                     tip: "Mih-man",                     level: 2 },
      { uyghur: "خاتىرجەم",        latin: "Xatirem",         english: "At ease / Comfortable",     tip: "Xa-ti-rem",                   level: 3 },
      { uyghur: "خۇش كەپسىز",     latin: "Xush kepsiz",     english: "Welcome",                   tip: "Khush kep-siz",               level: 3 },
      { uyghur: "ئىسمىڭىز نېمە؟", latin: "Ismingiz néme?",  english: "What is your name?",        tip: "Is-ming-iz né-me",            level: 3 },
      { uyghur: "سەلامەتلىك",     latin: "Selamätlik",      english: "Good health (greeting)",    tip: "Se-la-met-lik",               level: 4 },
    ],
    numbers: [
      { uyghur: "بىر",      latin: "Bir",      english: "1 — One",       tip: "Beer",          level: 1 },
      { uyghur: "ئىككى",   latin: "Ikki",     english: "2 — Two",       tip: "Ik-ki",         level: 1 },
      { uyghur: "ئۈچ",     latin: "Üch",      english: "3 — Three",     tip: "Üch",           level: 1 },
      { uyghur: "تۆت",     latin: "Töt",      english: "4 — Four",      tip: "Töt",           level: 1 },
      { uyghur: "بەش",     latin: "Besh",     english: "5 — Five",      tip: "Besh",          level: 1 },
      { uyghur: "ئالتە",   latin: "Alte",     english: "6 — Six",       tip: "Al-te",         level: 2 },
      { uyghur: "يەتتە",   latin: "Yette",    english: "7 — Seven",     tip: "Yet-te",        level: 2 },
      { uyghur: "سەككىز",  latin: "Sekkiz",   english: "8 — Eight",     tip: "Sek-kiz",       level: 2 },
      { uyghur: "توققۇز",  latin: "Toqquz",   english: "9 — Nine",      tip: "Toq-quz",       level: 2 },
      { uyghur: "ئون",     latin: "On",       english: "10 — Ten",      tip: "On",            level: 2 },
      { uyghur: "ئون بىر", latin: "On bir",   english: "11 — Eleven",   tip: "On beer",       level: 3 },
      { uyghur: "ئون ئىككى",latin:"On ikki",  english: "12 — Twelve",   tip: "On ik-ki",      level: 3 },
      { uyghur: "يىگىرمە", latin: "Yigirme",  english: "20 — Twenty",   tip: "Yi-gir-me",     level: 3 },
      { uyghur: "ئوتتۇز",  latin: "Ottuz",    english: "30 — Thirty",   tip: "Ot-tuz",        level: 3 },
      { uyghur: "قىرىق",   latin: "Qiriq",    english: "40 — Forty",    tip: "Qi-riq",        level: 4 },
      { uyghur: "ئەللىك",  latin: "Ellik",    english: "50 — Fifty",    tip: "El-lik",        level: 4 },
      { uyghur: "يۈز",     latin: "Yüz",      english: "100 — Hundred", tip: "Yüz",           level: 4 },
      { uyghur: "مىڭ",     latin: "Ming",     english: "1000 — Thousand",tip: "Ming",         level: 5 },
      { uyghur: "نۆل",     latin: "Nöl",      english: "0 — Zero",      tip: "Nöl",           level: 5 },
      { uyghur: "مىليون",  latin: "Milyon",   english: "Million",        tip: "Mil-yon",       level: 6 },
    ],
    family: [
      { uyghur: "دادا",    latin: "Dada",     english: "Father",           tip: "Da-da",       level: 1 },
      { uyghur: "ئانا",    latin: "Ana",      english: "Mother",           tip: "A-na",        level: 1 },
      { uyghur: "ئاكا",    latin: "Aka",      english: "Older brother",    tip: "A-ka",        level: 1 },
      { uyghur: "ئاچە",    latin: "Ache",     english: "Older sister",     tip: "A-che",       level: 1 },
      { uyghur: "ئىنى",    latin: "Ini",      english: "Younger brother",  tip: "I-ni",        level: 2 },
      { uyghur: "سىڭىل",   latin: "Singil",   english: "Younger sister",   tip: "Sin-gil",     level: 2 },
      { uyghur: "بوۋى",    latin: "Buwi",     english: "Grandfather",      tip: "Bu-wi",       level: 2 },
      { uyghur: "موما",    latin: "Moma",     english: "Grandmother",      tip: "Mo-ma",       level: 2 },
      { uyghur: "ئوغۇل",   latin: "Oghul",    english: "Son",              tip: "Og-hul",      level: 3 },
      { uyghur: "قىز",     latin: "Qiz",      english: "Daughter / Girl",  tip: "Qiz",         level: 3 },
      { uyghur: "ئامما",   latin: "Amma",     english: "Paternal aunt",    tip: "Am-ma",       level: 3 },
      { uyghur: "تاغا",    latin: "Tagha",    english: "Maternal uncle",   tip: "Ta-gha",      level: 3 },
      { uyghur: "ئائىلە",  latin: "Ayile",    english: "Family",           tip: "A-yi-le",     level: 3 },
      { uyghur: "ئەر",     latin: "Er",       english: "Husband",          tip: "Er",          level: 4 },
      { uyghur: "خوتۇن",   latin: "Xotun",    english: "Wife",             tip: "Xo-tun",      level: 4 },
      { uyghur: "بالا",    latin: "Bala",     english: "Child",            tip: "Ba-la",       level: 4 },
      { uyghur: "نەۋرە",   latin: "Newre",    english: "Grandchild",       tip: "New-re",      level: 5 },
      { uyghur: "ئاتا",    latin: "Ata",      english: "Ancestor / Father (formal)", tip: "A-ta", level: 5 },
    ],
    colors: [
      { uyghur: "قىزىل",      latin: "Qizil",     english: "Red",          tip: "Qi-zil",       level: 1 },
      { uyghur: "يېشىل",      latin: "Yéshil",    english: "Green",        tip: "Yé-shil",      level: 1 },
      { uyghur: "كۆك",        latin: "Kök",       english: "Blue",         tip: "Kök",          level: 1 },
      { uyghur: "سېرىق",      latin: "Sériq",     english: "Yellow",       tip: "Sé-riq",       level: 1 },
      { uyghur: "ئاق",        latin: "Aq",        english: "White",        tip: "Aq",           level: 2 },
      { uyghur: "قارا",       latin: "Qara",      english: "Black",        tip: "Qa-ra",        level: 2 },
      { uyghur: "توق سېرىق",  latin: "Toq sériq", english: "Orange",       tip: "Toq sé-riq",   level: 3 },
      { uyghur: "بىنەپشە",    latin: "Binepshé",  english: "Purple",       tip: "Bi-nep-shé",   level: 3 },
      { uyghur: "كۆكچە",      latin: "Kökshe",    english: "Light blue",   tip: "Kök-she",      level: 3 },
      { uyghur: "قوڭۇر",      latin: "Qongur",    english: "Brown",        tip: "Qon-gur",      level: 4 },
      { uyghur: "كۈمۈش",      latin: "Kümüsh",    english: "Silver",       tip: "Kü-müsh",      level: 4 },
      { uyghur: "ئالتۇن",     latin: "Altun",     english: "Gold / Golden",tip: "Al-tun",       level: 4 },
    ],
    food: [
      { uyghur: "سۇ",        latin: "Su",        english: "Water",              tip: "Su",           level: 1 },
      { uyghur: "نان",       latin: "Nan",       english: "Bread / Naan",       tip: "Nan",          level: 1 },
      { uyghur: "گۆش",      latin: "Gösh",      english: "Meat",               tip: "Gösh",         level: 1 },
      { uyghur: "چاي",       latin: "Chay",      english: "Tea",                tip: "Chay",         level: 1 },
      { uyghur: "ئالما",     latin: "Alma",      english: "Apple",              tip: "Al-ma",        level: 2 },
      { uyghur: "ئۈزۈم",    latin: "Üzüm",      english: "Grape",              tip: "Ü-züm",        level: 2 },
      { uyghur: "پولو",      latin: "Polo",      english: "Pilaf / Rice dish",  tip: "Po-lo",        level: 2 },
      { uyghur: "شىكەر",     latin: "Shiker",    english: "Sugar",              tip: "Shi-ker",      level: 2 },
      { uyghur: "يۇمۇرتقا", latin: "Yumurtqa",  english: "Egg",                tip: "Yu-murt-qa",   level: 3 },
      { uyghur: "تاۋاق",     latin: "Tawaq",     english: "Dish / Plate",       tip: "Ta-waq",       level: 3 },
      { uyghur: "سامسا",     latin: "Samsa",     english: "Samsa (pastry)",     tip: "Sam-sa",       level: 3 },
      { uyghur: "لەغمەن",    latin: "Leghmen",   english: "Lagman (noodles)",   tip: "Leg-men",      level: 3 },
      { uyghur: "مىۋە",      latin: "Miwe",      english: "Fruit",              tip: "Mi-we",        level: 3 },
      { uyghur: "سۈت",       latin: "Süt",       english: "Milk",               tip: "Süt",          level: 4 },
      { uyghur: "ياغ",       latin: "Yagh",      english: "Oil / Fat / Butter", tip: "Yagh",         level: 4 },
      { uyghur: "تۇز",       latin: "Tuz",       english: "Salt",               tip: "Tuz",          level: 4 },
      { uyghur: "ئەرزە",     latin: "Erze",      english: "Noodle dough",       tip: "Er-ze",        level: 5 },
      { uyghur: "كاۋاپ",     latin: "Kawap",     english: "Kebab",              tip: "Ka-wap",       level: 5 },
    ],
    animals: [
      { uyghur: "ئات",       latin: "At",       english: "Horse",      tip: "At",          level: 1 },
      { uyghur: "ئىت",       latin: "It",       english: "Dog",        tip: "It",          level: 1 },
      { uyghur: "مۈشۈك",    latin: "Müshük",   english: "Cat",        tip: "Mü-shük",     level: 1 },
      { uyghur: "قوي",       latin: "Qoy",      english: "Sheep",      tip: "Qoy",         level: 1 },
      { uyghur: "توخۇ",      latin: "Toxu",     english: "Chicken",    tip: "To-xu",       level: 2 },
      { uyghur: "قۇش",      latin: "Qush",     english: "Bird",       tip: "Qush",        level: 2 },
      { uyghur: "بالىق",     latin: "Baliq",    english: "Fish",       tip: "Ba-liq",      level: 2 },
      { uyghur: "ئايىق",     latin: "Ayiq",     english: "Bear",       tip: "A-yiq",       level: 2 },
      { uyghur: "ئارسلان",   latin: "Arslan",   english: "Lion",       tip: "Ars-lan",     level: 3 },
      { uyghur: "پىل",       latin: "Pil",      english: "Elephant",   tip: "Pil",         level: 3 },
      { uyghur: "بۆرە",      latin: "Böre",     english: "Wolf",       tip: "Bö-re",       level: 3 },
      { uyghur: "تۈلكە",     latin: "Tülke",    english: "Fox",        tip: "Tül-ke",      level: 3 },
      { uyghur: "ئۇيان",     latin: "Uyan",     english: "Rabbit",     tip: "U-yan",       level: 4 },
      { uyghur: "كىيىك",     latin: "Kiyik",    english: "Deer / Gazelle",tip: "Ki-yik",  level: 4 },
      { uyghur: "قارچىغاي",  latin: "Qarchighay",english: "Eagle",     tip: "Qar-chi-ghay",level: 5 },
    ],
    body: [
      { uyghur: "باش",      latin: "Bash",     english: "Head",          tip: "Bash",       level: 1 },
      { uyghur: "كۆز",      latin: "Köz",      english: "Eye",           tip: "Köz",        level: 1 },
      { uyghur: "قول",      latin: "Qol",      english: "Hand / Arm",    tip: "Qol",        level: 1 },
      { uyghur: "ئاياق",    latin: "Ayaq",     english: "Foot / Leg",    tip: "A-yaq",      level: 1 },
      { uyghur: "قۇلاق",    latin: "Qulaq",    english: "Ear",           tip: "Qu-laq",     level: 2 },
      { uyghur: "بۇرۇن",    latin: "Burun",    english: "Nose",          tip: "Bu-run",     level: 2 },
      { uyghur: "ئاغىز",    latin: "Aghiz",    english: "Mouth",         tip: "Ag-hiz",     level: 2 },
      { uyghur: "يۈرەك",    latin: "Yürek",    english: "Heart",         tip: "Yü-rek",     level: 2 },
      { uyghur: "چاچ",      latin: "Chach",    english: "Hair",          tip: "Chach",      level: 3 },
      { uyghur: "تىش",      latin: "Tish",     english: "Tooth",         tip: "Tish",       level: 3 },
      { uyghur: "بوين",     latin: "Boyin",    english: "Neck",          tip: "Bo-yin",     level: 3 },
      { uyghur: "يۈز",      latin: "Yüz",      english: "Face",          tip: "Yüz — also means 100!", level: 3 },
      { uyghur: "تىل",      latin: "Til",      english: "Tongue / Language",tip: "Til",    level: 4 },
      { uyghur: "قان",      latin: "Qan",      english: "Blood",         tip: "Qan",        level: 4 },
      { uyghur: "بەل",      latin: "Bel",      english: "Waist / Back",  tip: "Bel",        level: 5 },
    ],
    clothing: [
      { uyghur: "دوپپا",       latin: "Doppa",      english: "Uyghur cap (doppa)",   tip: "Dop-pa — iconic Uyghur hat",         level: 1 },
      { uyghur: "كۆيلەك",      latin: "Köylek",     english: "Dress / Shirt",         tip: "Köy-lek",                            level: 1 },
      { uyghur: "شىم",         latin: "Shim",       english: "Trousers / Pants",      tip: "Shim",                               level: 1 },
      { uyghur: "كىيىم",       latin: "Kiyim",      english: "Clothes / Garment",     tip: "Ki-yim — general word for clothing", level: 1 },
      { uyghur: "پايپاق",      latin: "Paypaq",     english: "Socks / Stockings",     tip: "Pay-paq",                            level: 2 },
      { uyghur: "ئەتەك",       latin: "Etek",       english: "Skirt",                 tip: "E-tek",                              level: 2 },
      { uyghur: "ئۆتۈك",       latin: "Ötük",       english: "Boots / Shoes",         tip: "Ö-tük",                              level: 2 },
      { uyghur: "كامزۇل",      latin: "Kamzul",     english: "Vest / Waistcoat",      tip: "Kam-zul — worn over the shirt",      level: 3 },
      { uyghur: "تون",         latin: "Tun",        english: "Padded robe / Coat",    tip: "Tun — traditional Uyghur winter coat",level: 3 },
      { uyghur: "ئورامال",     latin: "Oramal",     english: "Scarf / Handkerchief",  tip: "O-ra-mal",                           level: 4 },
      { uyghur: "بەلۋاغ",      latin: "Belwagh",    english: "Belt / Sash",           tip: "Bel-wagh",                           level: 4 },
      { uyghur: "جۇببە",       latin: "Jubbe",      english: "Long robe (jubba)",     tip: "Jub-be — formal Islamic gown",       level: 5 },
    ],
    nature: [
      { uyghur: "كۈن",         latin: "Kün",        english: "Sun / Day",            tip: "Kün — also means 'day'",              level: 1 },
      { uyghur: "ئاي",         latin: "Ay",         english: "Moon / Month",         tip: "Ay — also means 'month'",             level: 1 },
      { uyghur: "يۇلتۇز",      latin: "Yultuz",     english: "Star",                 tip: "Yul-tuz",                             level: 1 },
      { uyghur: "سۇ",          latin: "Su",         english: "Water / River",        tip: "Su",                                  level: 1 },
      { uyghur: "تاغ",         latin: "Tagh",       english: "Mountain",             tip: "Tagh",                                level: 2 },
      { uyghur: "دەريا",       latin: "Derya",      english: "River",                tip: "Der-ya",                              level: 2 },
      { uyghur: "ياغمۇر",      latin: "Yaghmur",    english: "Rain",                 tip: "Yagh-mur",                            level: 2 },
      { uyghur: "قار",         latin: "Qar",        english: "Snow",                 tip: "Qar",                                 level: 2 },
      { uyghur: "شامال",       latin: "Shamal",     english: "Wind",                 tip: "Sha-mal",                             level: 3 },
      { uyghur: "ئورمان",      latin: "Orman",      english: "Forest / Woods",       tip: "Or-man",                              level: 3 },
      { uyghur: "كۆل",         latin: "Köl",        english: "Lake",                 tip: "Köl",                                 level: 3 },
      { uyghur: "ئاسمان",      latin: "Asman",      english: "Sky",                  tip: "As-man",                              level: 3 },
      { uyghur: "يەر",         latin: "Yer",        english: "Earth / Ground",       tip: "Yer",                                 level: 3 },
      { uyghur: "چۆل",         latin: "Chöl",       english: "Desert / Steppe",      tip: "Chöl — Central Asian grassland",      level: 4 },
      { uyghur: "گۈل",         latin: "Gül",        english: "Flower",               tip: "Gül",                                 level: 4 },
      { uyghur: "داراخت",      latin: "Daraxt",     english: "Tree",                 tip: "Da-raxt",                             level: 4 },
      { uyghur: "بۇلاق",       latin: "Bulaq",      english: "Spring / Fountain",    tip: "Bu-laq",                              level: 5 },
      { uyghur: "قىياق",       latin: "Qiyaq",      english: "Cliff / Rocky slope",  tip: "Qi-yaq",                              level: 5 },
    ],
    school: [
      { uyghur: "مەكتەپ",      latin: "Mektep",      english: "School",              tip: "Mek-tep",                             level: 1 },
      { uyghur: "كىتاب",       latin: "Kitab",       english: "Book",                tip: "Ki-tab",                              level: 1 },
      { uyghur: "قەلەم",       latin: "Qelem",       english: "Pen / Pencil",        tip: "Qe-lem",                              level: 1 },
      { uyghur: "خالتا",       latin: "Xalta",       english: "Bag / Backpack",      tip: "Xal-ta",                              level: 1 },
      { uyghur: "ئوقۇتقۇچى",  latin: "Oqutquchi",   english: "Teacher",             tip: "O-qut-qu-chi",                        level: 2 },
      { uyghur: "ئوقۇغۇچى",   latin: "Oqughuchi",   english: "Student",             tip: "O-qugh-u-chi",                        level: 2 },
      { uyghur: "دەرس",        latin: "Ders",        english: "Lesson / Class",      tip: "Ders",                                level: 2 },
      { uyghur: "تاختا",       latin: "Taxta",       english: "Blackboard",          tip: "Tax-ta",                              level: 2 },
      { uyghur: "ئىمتىھان",    latin: "Imtihan",     english: "Exam / Test",         tip: "Im-ti-han — from Arabic",             level: 3 },
      { uyghur: "مەكتەپخانا", latin: "Mektepxana",  english: "Classroom",           tip: "Mek-tep-xa-na",                       level: 3 },
      { uyghur: "ئوقۇش",       latin: "Oqush",       english: "Reading / Study",     tip: "O-qush",                              level: 3 },
      { uyghur: "يازماق",      latin: "Yazmaq",      english: "To write",            tip: "Yaz-maq",                             level: 3 },
      { uyghur: "ئالىم",       latin: "Alim",        english: "Scholar / Scientist", tip: "A-lim — from Arabic",                 level: 4 },
      { uyghur: "ئۇنىۋېرسىتېت",latin:"Uniwérsitét",  english: "University",          tip: "U-ni-wer-si-tet",                     level: 4 },
      { uyghur: "دەرسلىك",     latin: "Derslik",     english: "Textbook",            tip: "Ders-lik",                            level: 5 },
    ],
    home: [
      { uyghur: "ئۆي",         latin: "Öy",          english: "House / Home",         tip: "Öy",                                  level: 1 },
      { uyghur: "ئىشىك",       latin: "Ishik",       english: "Door",                 tip: "I-shik",                              level: 1 },
      { uyghur: "دەرىچە",      latin: "Deriche",     english: "Window",               tip: "De-ri-che",                           level: 1 },
      { uyghur: "ستول",        latin: "Stol",        english: "Table",                tip: "Stol — from Russian",                 level: 1 },
      { uyghur: "ئاشخانا",     latin: "Ashxana",     english: "Kitchen",              tip: "Ash-xa-na — ash means food",          level: 2 },
      { uyghur: "ئۇيقۇخانا",  latin: "Uyquxana",    english: "Bedroom",              tip: "Uy-qu-xa-na",                         level: 2 },
      { uyghur: "ھاممام",      latin: "Hammam",      english: "Bathroom",             tip: "Ham-mam — from Arabic",               level: 2 },
      { uyghur: "ئولتۇرغۇچ",  latin: "Olturghuch",  english: "Chair",                tip: "Ol-tur-ghuch",                        level: 2 },
      { uyghur: "كارىۋات",     latin: "Kariwat",     english: "Bed",                  tip: "Ka-ri-wat",                           level: 3 },
      { uyghur: "كۆرپە",       latin: "Körpe",       english: "Blanket / Quilt",      tip: "Kör-pe — traditional Uyghur quilt",  level: 3 },
      { uyghur: "يوقان",       latin: "Yoghan",      english: "Pillow",               tip: "Yo-ghan",                             level: 3 },
      { uyghur: "قازان",       latin: "Qazan",       english: "Cooking Pot",          tip: "Qa-zan",                              level: 3 },
      { uyghur: "پىچاق",       latin: "Pichaq",      english: "Knife",                tip: "Pi-chaq",                             level: 4 },
      { uyghur: "قوشۇق",       latin: "Qoshuq",      english: "Spoon",                tip: "Qo-shuq",                             level: 4 },
      { uyghur: "لامپا",       latin: "Lampa",       english: "Lamp / Light",         tip: "Lam-pa — from Russian",               level: 4 },
      { uyghur: "توشاك",       latin: "Toshak",      english: "Mattress",             tip: "To-shak — traditional sleeping mat",  level: 4 },
      { uyghur: "گىلەم",       latin: "Gilem",       english: "Carpet / Rug",         tip: "Gi-lem — Uyghur carpets are famous",  level: 5 },
      { uyghur: "تاۋان",       latin: "Tawan",       english: "Ceiling / Roof",       tip: "Ta-wan",                              level: 5 },
      { uyghur: "سۈپۈرگە",     latin: "Süpürge",     english: "Broom",                tip: "Sü-pür-ge",                           level: 5 },
      { uyghur: "ئاينا",       latin: "Ayna",        english: "Mirror",               tip: "Ay-na — from Persian",                level: 5 },
    ],
    time: [
      { uyghur: "بۈگۈن",       latin: "Bügün",       english: "Today",                tip: "Bü-gün",                              level: 1 },
      { uyghur: "ئەتە",        latin: "Ete",         english: "Tomorrow",             tip: "E-te",                                level: 1 },
      { uyghur: "تۈنۈگۈن",    latin: "Tünügün",     english: "Yesterday",            tip: "Tü-nü-gün",                           level: 1 },
      { uyghur: "ئەتىگەن",    latin: "Etigen",      english: "Morning",              tip: "E-ti-gen",                            level: 1 },
      { uyghur: "كەچ",         latin: "Kech",        english: "Evening",              tip: "Kech",                                level: 1 },
      { uyghur: "ھازىر",       latin: "Hazir",       english: "Now",                  tip: "Ha-zir",                              level: 2 },
      { uyghur: "كېيىن",       latin: "Kéyin",       english: "Later / After",        tip: "Ké-yin",                              level: 2 },
      { uyghur: "ھەپتە",       latin: "Hepte",       english: "Week",                 tip: "Hep-te",                              level: 2 },
      { uyghur: "دۈشەنبە",     latin: "Düshenbe",    english: "Monday",               tip: "Dü-shen-be",                          level: 2 },
      { uyghur: "سەيشەنبە",    latin: "Seyshenbe",   english: "Tuesday",              tip: "Sey-shen-be",                         level: 3 },
      { uyghur: "چارشەنبە",    latin: "Charshenbe",  english: "Wednesday",            tip: "Char-shen-be",                        level: 3 },
      { uyghur: "پەيشەنبە",    latin: "Peyshenbe",   english: "Thursday",             tip: "Pey-shen-be",                         level: 3 },
      { uyghur: "جۈمە",        latin: "Jüme",        english: "Friday (holy day)",    tip: "Jü-me",                               level: 3 },
      { uyghur: "شەنبە",       latin: "Shenbe",      english: "Saturday",             tip: "Shen-be",                             level: 3 },
      { uyghur: "يەكشەنبە",    latin: "Yekshenbe",   english: "Sunday",               tip: "Yek-shen-be",                         level: 4 },
      { uyghur: "دەقىقە",      latin: "Deqiqe",      english: "Minute",               tip: "De-qi-qe",                            level: 4 },
      { uyghur: "يىل",         latin: "Yil",         english: "Year",                 tip: "Yil",                                 level: 4 },
      { uyghur: "قىش",         latin: "Qish",        english: "Winter",               tip: "Qish",                                level: 4 },
      { uyghur: "ياز",         latin: "Yaz",         english: "Summer",               tip: "Yaz — also means 'to write'!",        level: 4 },
      { uyghur: "كۈز",         latin: "Küz",         english: "Autumn / Fall",        tip: "Küz",                                 level: 5 },
      { uyghur: "بەھار",       latin: "Behar",       english: "Spring",               tip: "Be-har — from Persian",               level: 5 },
    ],
    adjectives: [
      { uyghur: "چوڭ",         latin: "Chong",       english: "Big / Large",          tip: "Chong",                               level: 1 },
      { uyghur: "كىچىك",       latin: "Kichik",      english: "Small / Little",       tip: "Ki-chik",                             level: 1 },
      { uyghur: "ئۇزۇن",       latin: "Uzun",        english: "Long / Tall",          tip: "U-zun",                               level: 1 },
      { uyghur: "كەلتە",       latin: "Kelte",       english: "Short",                tip: "Kel-te",                              level: 1 },
      { uyghur: "يېڭى",        latin: "Yéngi",       english: "New",                  tip: "Yé-ngi",                              level: 1 },
      { uyghur: "كونا",        latin: "Kona",        english: "Old (for things)",     tip: "Ko-na",                               level: 2 },
      { uyghur: "چىرايلىق",    latin: "Chiraylik",   english: "Beautiful / Pretty",   tip: "Chi-ray-liq",                         level: 2 },
      { uyghur: "ئىسسىق",      latin: "Issiq",       english: "Hot / Warm",           tip: "Is-siq",                              level: 2 },
      { uyghur: "سوغاق",       latin: "Soghaq",      english: "Cold",                 tip: "So-ghaq",                             level: 2 },
      { uyghur: "ئاسان",       latin: "Asan",        english: "Easy",                 tip: "A-san",                               level: 2 },
      { uyghur: "قىيىن",       latin: "Qiyin",       english: "Difficult / Hard",     tip: "Qi-yin",                              level: 3 },
      { uyghur: "ئارزان",      latin: "Arzan",       english: "Cheap",                tip: "Ar-zan",                              level: 3 },
      { uyghur: "قىممەت",      latin: "Qimmet",      english: "Expensive",            tip: "Qim-met",                             level: 3 },
      { uyghur: "يىراق",       latin: "Yiraq",       english: "Far",                  tip: "Yi-raq",                              level: 3 },
      { uyghur: "يېقىن",       latin: "Yéqin",       english: "Near / Close",         tip: "Yé-qin",                              level: 3 },
      { uyghur: "ئاغىر",       latin: "Aghir",       english: "Heavy",                tip: "Ag-hir",                              level: 4 },
      { uyghur: "يېنىك",       latin: "Yénik",       english: "Light (in weight)",    tip: "Yé-nik",                              level: 4 },
      { uyghur: "تولۇق",       latin: "Toliiq",      english: "Full / Complete",      tip: "To-liq",                              level: 4 },
      { uyghur: "بوش",         latin: "Bosh",        english: "Empty",                tip: "Bosh — also means 'head'!",           level: 4 },
      { uyghur: "مەزە",        latin: "Meze",        english: "Delicious",            tip: "Me-ze — top Uyghur food compliment",  level: 4 },
      { uyghur: "ئاستە",       latin: "Aste",        english: "Slow",                 tip: "As-te",                               level: 5 },
      { uyghur: "تىز",         latin: "Tiz",         english: "Fast / Quick",         tip: "Tiz",                                 level: 5 },
      { uyghur: "باشقا",       latin: "Bashqa",      english: "Different / Other",    tip: "Bash-qa",                             level: 5 },
      { uyghur: "ئوخشاش",      latin: "Oxshash",     english: "Same / Similar",       tip: "Ox-shash",                            level: 6 },
    ],
    verbs: [
      { uyghur: "بارماق",      latin: "Barmaq",      english: "To go",                tip: "Bar-maq",                             level: 1 },
      { uyghur: "كەلمەك",      latin: "Kelmek",      english: "To come",              tip: "Kel-mek",                             level: 1 },
      { uyghur: "يېيىش",       latin: "Yeyish",      english: "To eat",               tip: "Ye-yish",                             level: 1 },
      { uyghur: "ئىچمەك",      latin: "Ichmek",      english: "To drink",             tip: "Ich-mek",                             level: 1 },
      { uyghur: "كۆرمەك",      latin: "Körmek",      english: "To see / watch",       tip: "Kör-mek",                             level: 1 },
      { uyghur: "سۆزلىمەك",    latin: "Sözlimek",    english: "To speak",             tip: "Söz-li-mek",                          level: 2 },
      { uyghur: "ئوقۇماق",     latin: "Oqumaq",      english: "To read / study",      tip: "O-qu-maq",                            level: 2 },
      { uyghur: "يازماق",      latin: "Yazmaq",      english: "To write",             tip: "Yaz-maq",                             level: 2 },
      { uyghur: "ئاڭلىماق",    latin: "Anghlimaq",   english: "To listen / hear",     tip: "Ang-hli-maq",                         level: 2 },
      { uyghur: "ئالماق",      latin: "Almaq",       english: "To buy / take",        tip: "Al-maq",                              level: 2 },
      { uyghur: "بەرمەك",      latin: "Bermek",      english: "To give",              tip: "Ber-mek",                             level: 3 },
      { uyghur: "قىلماق",      latin: "Qilmaq",      english: "To do / make",         tip: "Qil-maq — the most common Uyghur verb",level: 3 },
      { uyghur: "بىلمەك",      latin: "Bilmek",      english: "To know",              tip: "Bil-mek",                             level: 3 },
      { uyghur: "سۆيمەك",      latin: "Söymek",      english: "To love",              tip: "Söy-mek",                             level: 3 },
      { uyghur: "ئولتۇرماق",   latin: "Olturmaq",    english: "To sit",               tip: "Ol-tur-maq",                          level: 3 },
      { uyghur: "تۇرماق",      latin: "Turmaq",      english: "To stand / get up",    tip: "Tur-maq",                             level: 4 },
      { uyghur: "ئاچماق",      latin: "Achmaq",      english: "To open",              tip: "Ach-maq",                             level: 4 },
      { uyghur: "يۇيماق",      latin: "Yuymaq",      english: "To wash",              tip: "Yuy-maq",                             level: 4 },
      { uyghur: "كىيمەك",      latin: "Kiymek",      english: "To wear / put on",     tip: "Kiy-mek",                             level: 4 },
      { uyghur: "قارىماق",     latin: "Qarimaq",     english: "To look",              tip: "Qa-ri-maq",                           level: 4 },
      { uyghur: "ئويلىماق",    latin: "Oyimaq",      english: "To think",             tip: "Oy-li-maq",                           level: 5 },
      { uyghur: "قايتماق",     latin: "Qaytmaq",     english: "To return",            tip: "Qayt-maq",                            level: 5 },
      { uyghur: "باشلاشماق",   latin: "Bashlashmaq", english: "To start / begin",     tip: "Bash-lash-maq",                       level: 5 },
      { uyghur: "توختاشماق",   latin: "Toxtashmaq",  english: "To stop",              tip: "Tox-tash-maq",                        level: 6 },
    ],
    city: [
      { uyghur: "بازار",       latin: "Bazar",       english: "Bazaar / Market",      tip: "Ba-zar — heart of every Uyghur city", level: 1 },
      { uyghur: "دوكان",       latin: "Dokan",       english: "Shop / Store",         tip: "Do-kan",                              level: 1 },
      { uyghur: "كوچا",        latin: "Kocha",       english: "Street",               tip: "Ko-cha",                              level: 1 },
      { uyghur: "مەسچىت",      latin: "Mesjit",      english: "Mosque",               tip: "Mes-jit — center of Uyghur community",level: 1 },
      { uyghur: "مەيدان",      latin: "Meydan",      english: "Square / Plaza",       tip: "Mey-dan — from Persian",              level: 2 },
      { uyghur: "پارك",        latin: "Park",        english: "Park",                 tip: "Park",                                level: 2 },
      { uyghur: "دوختۇرخانا",  latin: "Doxtarxana",  english: "Clinic / Hospital",    tip: "Dox-tur-xa-na",                       level: 2 },
      { uyghur: "كۇتۇپخانا",   latin: "Kutupxana",   english: "Library",              tip: "Ku-tup-xa-na",                        level: 3 },
      { uyghur: "رىستوران",    latin: "Ristoran",    english: "Restaurant",           tip: "Ris-to-ran — from Russian",           level: 3 },
      { uyghur: "مېھمانخانا",  latin: "Mehmunxana",  english: "Hotel",                tip: "Meh-mun-xa-na — mehmun = guest",      level: 3 },
      { uyghur: "پوچتا",       latin: "Pochta",      english: "Post Office",          tip: "Poch-ta — from Russian",              level: 3 },
      { uyghur: "داروخانا",    latin: "Daruxana",    english: "Pharmacy",             tip: "Da-ru-xa-na — daru = medicine",       level: 4 },
      { uyghur: "ئايروپورت",   latin: "Ayropport",   english: "Airport",              tip: "Ay-ro-port",                          level: 4 },
      { uyghur: "ۋاگزال",      latin: "Wagzal",      english: "Train Station",        tip: "Wag-zal — from Russian 'vokzal'",     level: 4 },
      { uyghur: "كۆۋرۈك",      latin: "Köwrük",      english: "Bridge",               tip: "Köw-rük",                             level: 5 },
      { uyghur: "مەھەللە",     latin: "Mehelle",     english: "Neighborhood",         tip: "Me-hel-le — Uyghur community quarter",level: 5 },
    ],
    emotions: [
      { uyghur: "خۇشاللىق",    latin: "Xushalliq",   english: "Happiness / Joy",      tip: "Xu-shal-liq",                         level: 1 },
      { uyghur: "غەم",         latin: "Ghem",        english: "Sorrow / Sadness",     tip: "Ghem",                                level: 2 },
      { uyghur: "ئاچچىق",      latin: "Achiiq",      english: "Anger",                tip: "Ach-chiq",                            level: 2 },
      { uyghur: "قورقۇنچ",     latin: "Qorqunch",    english: "Fear",                 tip: "Qor-qunch",                           level: 2 },
      { uyghur: "چارچاق",      latin: "Charchiaq",   english: "Tired / Fatigue",      tip: "Char-chaq",                           level: 2 },
      { uyghur: "ئۈمىد",       latin: "Ümid",        english: "Hope",                 tip: "Ü-mid — from Persian",                level: 3 },
      { uyghur: "سۆيگۈ",       latin: "Söygü",       english: "Love (noun)",          tip: "Söy-gü",                              level: 3 },
      { uyghur: "ھايران",      latin: "Hayran",      english: "Amazed / Surprised",   tip: "Hay-ran — from Arabic",               level: 3 },
      { uyghur: "يالغۇز",      latin: "Yalghuz",     english: "Lonely / Alone",       tip: "Yal-ghuz",                            level: 4 },
      { uyghur: "ئارزۇ",       latin: "Arzu",        english: "Wish / Desire",        tip: "Ar-zu — from Persian",                level: 4 },
      { uyghur: "ھەسرەت",      latin: "Hesret",      english: "Longing / Yearning",   tip: "Hes-ret — deep longing for homeland", level: 5 },
      { uyghur: "قايغۇ",       latin: "Qayghu",      english: "Worry / Grief",        tip: "Qay-ghu",                             level: 5 },
    ],
    transport: [
      { uyghur: "ئاپتوبۇس",    latin: "Aptobus",     english: "Bus",                  tip: "Ap-to-bus",                           level: 1 },
      { uyghur: "تاكسى",       latin: "Taksi",       english: "Taxi",                 tip: "Tak-si",                              level: 1 },
      { uyghur: "ۋېلىسىپىت",  latin: "Wélisipit",   english: "Bicycle",              tip: "Wé-li-si-pit",                        level: 1 },
      { uyghur: "پويىزد",      latin: "Poyizd",      english: "Train",                tip: "Po-yizd — from Russian",              level: 2 },
      { uyghur: "ئاييروپىلان", latin: "Ayroplian",   english: "Airplane",             tip: "Ay-ro-pli-an",                        level: 2 },
      { uyghur: "يول",         latin: "Yol",         english: "Road / Path",          tip: "Yol",                                 level: 2 },
      { uyghur: "توختاش",      latin: "Toxtash",     english: "Stop / Bus stop",      tip: "Tox-tash",                            level: 3 },
      { uyghur: "بىلەت",       latin: "Bilet",       english: "Ticket",               tip: "Bi-let — from Russian",               level: 3 },
      { uyghur: "كېمە",        latin: "Kéme",        english: "Boat / Ship",          tip: "Ké-me",                               level: 4 },
      { uyghur: "مۇسافىرلىق",  latin: "Musafirliq",  english: "Journey / Travel",     tip: "Mu-sa-fir-liq — from Arabic",         level: 5 },
    ],
  },

  phraseGroups: [
    {
      id: "greetings",
      name: "Greetings & Farewells",
      emoji: "👋",
      phrases: [
        { uyghur: "سالام!",                            latin: "Salam!",                             english: "Hello!" },
        { uyghur: "ئەسسالامۇئەلەيكۇم",                latin: "Essalamualéykum",                    english: "Peace be upon you (Islamic greeting)" },
        { uyghur: "ۋەئەلەيكۇم ئەسسالام",              latin: "We'éléykum essalam",                  english: "And upon you peace (response)" },
        { uyghur: "ياخشىمۇسىز؟",                      latin: "Yaxshimusiz?",                       english: "How are you? (formal)" },
        { uyghur: "ياخشى، رەھمەت. سىزچۇ؟",           latin: "Yaxshi, rehmet. Sizchu?",            english: "Fine, thank you. And you?" },
        { uyghur: "خەيىرلىك سەھەر!",                  latin: "Xeyirlik seher!",                    english: "Good morning!" },
        { uyghur: "خەيىرلىك كۈن!",                    latin: "Xeyirlik kün!",                      english: "Good day!" },
        { uyghur: "خەيىرلىك كەچ!",                    latin: "Xeyirlik kech!",                     english: "Good evening!" },
        { uyghur: "خۇش كەپسىز!",                      latin: "Xush kepsiz!",                       english: "Welcome!" },
        { uyghur: "خوش!",                              latin: "Xosh!",                              english: "Goodbye!" },
        { uyghur: "ئامان بولۇڭ",                       latin: "Aman bolung",                        english: "Take care / Be well" },
        { uyghur: "كۆرۈشكەنچە",                        latin: "Körüshkenche",                       english: "See you later" },
        { uyghur: "ئەتە كۆرۈشكەنچە",                  latin: "Ete körüshkenche",                   english: "See you tomorrow" },
        { uyghur: "ياخشى بولۇڭ!",                     latin: "Yaxshi bolung!",                     english: "Be well! (parting wish)" },
        { uyghur: "سائەت ياخشى بولسۇن",               latin: "Saet yaxshi bolsun",                 english: "Have a good time" },
      ]
    },
    {
      id: "introductions",
      name: "Introductions",
      emoji: "🤝",
      phrases: [
        { uyghur: "مىنىڭ ئىسمىم ___",                 latin: "Mening ismim ___",                   english: "My name is ___" },
        { uyghur: "سىزنىڭ ئىسمىڭىز نېمە؟",            latin: "Sizning ismingiz néme?",              english: "What is your name?" },
        { uyghur: "مەن ئۇيغۇر",                        latin: "Men uyghur",                         english: "I am Uyghur" },
        { uyghur: "مەن قايەردىنسىز؟",                  latin: "Men qeyerdinSiz?",                   english: "Where are you from?" },
        { uyghur: "مەن ئامېرىكىدىن",                  latin: "Men Amérikadin",                     english: "I am from America" },
        { uyghur: "مەن ئۈرۈمچىدىن",                   latin: "Men Ürümchidin",                     english: "I am from Ürümchi" },
        { uyghur: "مەن قانچە يېشىمدا؟",               latin: "Men qanche yéshimda?",               english: "How old am I?" },
        { uyghur: "مەن 25 يېشىمدا",                   latin: "Men 25 yéshimda",                    english: "I am 25 years old" },
        { uyghur: "سىز بىلەن تونۇشتۇم",               latin: "Siz bilen tonushtum",                english: "Nice to meet you" },
        { uyghur: "مەن ئۇيغۇرچە ئۆگىنىۋاتىمەن",      latin: "Men uyghurche öginiwatimen",         english: "I am learning Uyghur" },
        { uyghur: "مەن ئۇيغۇرچە بىلمەيمەن",           latin: "Men uyghurche bilmeyman",            english: "I don't know Uyghur" },
        { uyghur: "بىر ئاز بىلىمەن",                  latin: "Bir az bilimen",                     english: "I know a little" },
        { uyghur: "ئۇيغۇرچە دەرسىم بار",              latin: "Uyghurche dersim bar",               english: "I have Uyghur lessons" },
        { uyghur: "سىزنىڭ كەسپىڭىز نېمە؟",            latin: "Sizning kespingiz néme?",            english: "What is your profession?" },
        { uyghur: "مەن ئوقۇتقۇچى",                    latin: "Men oqutquchi",                      english: "I am a teacher" },
      ]
    },
    {
      id: "daily",
      name: "Daily Life",
      emoji: "🌅",
      phrases: [
        { uyghur: "بۈگۈن قانداق؟",                    latin: "Bügün qandaq?",                      english: "How is today?" },
        { uyghur: "مەن ئاچ",                           latin: "Men ach",                            english: "I am hungry" },
        { uyghur: "مەن تويدۇم",                        latin: "Men toydum",                         english: "I am full" },
        { uyghur: "مەن چاي ئىچىمەن",                  latin: "Men chay ichimen",                   english: "I drink tea" },
        { uyghur: "مەن نان يەيمەن",                    latin: "Men nan yeymen",                     english: "I eat bread" },
        { uyghur: "مەن ياتىمەن",                       latin: "Men yatimen",                        english: "I am going to sleep" },
        { uyghur: "مەكتەپكە بارىمەن",                  latin: "Mektepke barimen",                   english: "I go to school" },
        { uyghur: "ئىشتىن كەلدىم",                     latin: "Ishtin keldim",                      english: "I came from work" },
        { uyghur: "ئۆيدە ئولتۇرىمەن",                 latin: "Öyde olturimen",                     english: "I am sitting at home" },
        { uyghur: "ئەتىگەندە تۇرۇپ مەكتەپكە بارىمەن",latin: "Etigen turup mektepke barimen",      english: "I wake up in the morning and go to school" },
        { uyghur: "بۈگۈن ئىش كۆپ",                   latin: "Bügün ish köp",                      english: "There is a lot of work today" },
        { uyghur: "ئىش تاماملاندى",                   latin: "Ish tamamlandi",                     english: "The work is done" },
        { uyghur: "كۆمەك كەرەك",                       latin: "Kömek kerek",                        english: "Help is needed" },
        { uyghur: "بۇ نېمە؟",                          latin: "Bu néme?",                           english: "What is this?" },
        { uyghur: "ئۇ كىم؟",                           latin: "U kim?",                             english: "Who is that?" },
      ]
    },
    {
      id: "shopping",
      name: "Shopping & Market",
      emoji: "🛒",
      phrases: [
        { uyghur: "قانچە پۇل؟",                        latin: "Qanche pul?",                        english: "How much does it cost?" },
        { uyghur: "ئارزانراق بارمۇ؟",                  latin: "Arzanraq barmu?",                    english: "Is there something cheaper?" },
        { uyghur: "بۇنى مەن ئالىمەن",                 latin: "Buni men alimen",                    english: "I will take this" },
        { uyghur: "ئىككى تانە بېرىڭ",                 latin: "Ikki tane béring",                   english: "Give me two" },
        { uyghur: "باشقا رەڭ بارمۇ؟",                 latin: "Bashqa reng barmu?",                 english: "Is there another color?" },
        { uyghur: "يىرتىق، باشقا بارمۇ؟",            latin: "Yirtiq, bashqa barmu?",              english: "It's torn, do you have another?" },
        { uyghur: "بازارغا كەتتىم",                    latin: "Bazargha kettim",                    english: "I went to the market" },
        { uyghur: "ئالما قانچە؟",                      latin: "Alma qanche?",                       english: "How much are the apples?" },
        { uyghur: "ئىككى كىلو بېرىڭ",                latin: "Ikki kilo béring",                   english: "Give me two kilograms" },
        { uyghur: "مەن سوغالىمەن",                    latin: "Men soghálimen",                     english: "I am just looking" },
        { uyghur: "بۇنى قەيەردىن ئالدىڭىز؟",         latin: "Buni qeyerdin aldingiz?",            english: "Where did you get this?" },
        { uyghur: "خېرىدار",                           latin: "Xéridar",                            english: "Customer / Buyer" },
        { uyghur: "سودا",                              latin: "Soda",                               english: "Trade / Business" },
        { uyghur: "پۇل يوق",                           latin: "Pul yoq",                            english: "No money / Out of stock" },
        { uyghur: "رەھمەت، ئامان بولۇڭ",              latin: "Rehmet, aman bolung",                english: "Thank you, goodbye" },
      ]
    },
    {
      id: "food",
      name: "Food & Eating",
      emoji: "🍽️",
      phrases: [
        { uyghur: "پولو يېيىشنى ياخشى كۆرىمەن",      latin: "Polo yeyishni yaxshi körimen",       english: "I love eating polo (pilaf)" },
        { uyghur: "چاي ئىچىمسىز؟",                    latin: "Chay ichimsize?",                    english: "Will you drink tea?" },
        { uyghur: "ھەئە، رەھمەت",                     latin: "He'e, rehmet",                       english: "Yes, thank you" },
        { uyghur: "ناھايىتى مەزە!",                   latin: "Nahayiti meze!",                     english: "Very delicious!" },
        { uyghur: "بۇ نېمە ئاش؟",                     latin: "Bu néme ash?",                       english: "What dish is this?" },
        { uyghur: "يەنە بىر ئالسامچۇ؟",              latin: "Yne bir alsimchu?",                  english: "May I have another?" },
        { uyghur: "ئاشخانا قەيەردە؟",                 latin: "Ashxana qeyerde?",                   english: "Where is the restaurant?" },
        { uyghur: "سۇ بارمۇ؟",                        latin: "Su barmu?",                          english: "Is there water?" },
        { uyghur: "ئاچ قالدىم",                        latin: "Ach qaldim",                         english: "I got hungry" },
        { uyghur: "تويدۇق",                            latin: "Toyduq",                             english: "We are full" },
        { uyghur: "تاماق تەييارلاش",                  latin: "Tamaq teyyarlash",                   english: "Preparing food" },
        { uyghur: "ئۇيغۇر تاماقلىرى مەزە",           latin: "Uyghur tamaqliril meze",             english: "Uyghur food is delicious" },
        { uyghur: "مۇشۇ تاماقنىڭ ئىسمى نېمە؟",       latin: "Mushu tamaqning ismi néme?",         english: "What is the name of this dish?" },
        { uyghur: "بىر پىيالە چاي",                   latin: "Bir piyale chay",                    english: "One cup of tea" },
        { uyghur: "بىسمىللاھ",                        latin: "Bismillah",                          english: "In the name of God (before eating)" },
      ]
    },
    {
      id: "family",
      name: "Family & Home",
      emoji: "🏠",
      phrases: [
        { uyghur: "مىنىڭ دادام ياخشى ئادەم",         latin: "Mening dadam yaxshi adem",           english: "My father is a good man" },
        { uyghur: "ئانام مەنى سۆيىدۇ",               latin: "Anam meni söyidu",                   english: "My mother loves me" },
        { uyghur: "بىز بەش كىشىلىك ئائىلە",          latin: "Biz besh kishilik ayile",            english: "We are a family of five" },
        { uyghur: "ئائىلىڭىز قانچە كىشى؟",           latin: "Ayilingiz qanche kishi?",            english: "How many people are in your family?" },
        { uyghur: "ئاكام كۆمەك قىلىدۇ",              latin: "Akam kömek qilidu",                  english: "My older brother helps" },
        { uyghur: "سىڭىلىم مەكتەپتە",                latin: "Singilim mektepte",                  english: "My younger sister is at school" },
        { uyghur: "بوۋام 70 يېشىدا",                 latin: "Bowam 70 yéshida",                   english: "My grandfather is 70 years old" },
        { uyghur: "ئۆيىمىز چوڭ",                     latin: "Öyimiz chong",                       english: "Our house is big" },
        { uyghur: "ئۆيگە كەلىڭ",                     latin: "Öyge keling",                        english: "Come to our house" },
        { uyghur: "ئۆيدە كىم بار؟",                  latin: "Öyde kim bar?",                      english: "Who is at home?" },
        { uyghur: "بىز بۇ ئۆيدە تۇرىمىز",           latin: "Biz bu öyde turimiz",                english: "We live in this house" },
        { uyghur: "ئۆيدە نان بار",                   latin: "Öyde nan bar",                       english: "There is bread at home" },
        { uyghur: "دادام ئىشتا",                      latin: "Dadam ishta",                        english: "My father is at work" },
        { uyghur: "ئانام ئاشخانىدا",                  latin: "Anam ashxanida",                     english: "My mother is in the kitchen" },
        { uyghur: "بالىلىرىم مەكتەپتە",              latin: "Balilirim mektepte",                 english: "My children are at school" },
      ]
    },
    {
      id: "directions",
      name: "Directions & Travel",
      emoji: "🗺️",
      phrases: [
        { uyghur: "كەچۈرۈڭ، بازار قەيەردە؟",         latin: "Kechürüng, bazar qeyerde?",          english: "Excuse me, where is the bazaar?" },
        { uyghur: "ئالدىغا مېڭىڭ",                   latin: "Aldigha méning",                     english: "Go straight ahead" },
        { uyghur: "ئوڭغا بۇرۇلۇڭ",                   latin: "Ongha burulun",                      english: "Turn right" },
        { uyghur: "سولغا بۇرۇلۇڭ",                   latin: "Solgha burulun",                     english: "Turn left" },
        { uyghur: "ئۇزاقمۇ؟",                        latin: "Uzaqmu?",                            english: "Is it far?" },
        { uyghur: "يېقىن، پەقەت بەش دەقىقە",         latin: "Yéqin, peqet besh deqiqe",          english: "Close, only five minutes" },
        { uyghur: "ئاپتوبۇس بەكىتى قەيەردە؟",        latin: "Aptobus békiti qeyerde?",            english: "Where is the bus stop?" },
        { uyghur: "بىلەت قانچە؟",                    latin: "Bilet qanche?",                      english: "How much is the ticket?" },
        { uyghur: "تاكسى چاقىرالامسىز؟",             latin: "Taksi chaqiralamsiz?",               english: "Can you call a taxi?" },
        { uyghur: "ئايروپورت قەيەردە؟",              latin: "Ayropport qeyerde?",                 english: "Where is the airport?" },
        { uyghur: "مەكتەپكە قانداق بارىمەن؟",        latin: "Mektepke qandaq barimen?",           english: "How do I get to school?" },
        { uyghur: "يول باشلاپ بېرىڭ",               latin: "Yol bashlap béring",                 english: "Please lead the way" },
        { uyghur: "مەن ئادرىسىمنى ئۇنتىۋەتتىم",     latin: "Men adrisimni untiwetim",            english: "I forgot my address" },
        { uyghur: "پويىزد نەچچىدە كەتىدۇ؟",         latin: "Poyizd nechchide ketidu?",           english: "When does the train leave?" },
        { uyghur: "يول ئۇزاق ئەمەس",                latin: "Yol uzaq emes",                      english: "The road is not far" },
      ]
    },
    {
      id: "time",
      name: "Time & Numbers",
      emoji: "⏰",
      phrases: [
        { uyghur: "بۈگۈن نەچچى؟",                    latin: "Bügün nechchi?",                     english: "What is today's date?" },
        { uyghur: "بۈگۈن دۈشەنبە",                   latin: "Bügün Düshenbe",                     english: "Today is Monday" },
        { uyghur: "سائەت نەچچىدە؟",                  latin: "Saet nechchide?",                    english: "What time is it?" },
        { uyghur: "سائەت ئىككىدە",                   latin: "Saet ikkide",                        english: "It is two o'clock" },
        { uyghur: "يىغىن سائەت بەشتە",               latin: "Yighin saet beshte",                 english: "The meeting is at five o'clock" },
        { uyghur: "بىر ھەپتەدىن كېيىن",              latin: "Bir heptédin kéyin",                 english: "After one week" },
        { uyghur: "ئالتە سائەتتە يورۇيدۇ",           latin: "Alte saette yoruydu",                english: "It gets light at six o'clock" },
        { uyghur: "تۈنۈگۈن بالدۇر كەلدىم",           latin: "Tünügün baldur keldim",              english: "I came early yesterday" },
        { uyghur: "كىيىن ئويلىنىمىز",                latin: "Kéyin oylinimiz",                    english: "We'll think about it later" },
        { uyghur: "بۈگۈن يازغا كىردى",               latin: "Bügün yazgha kirdi",                 english: "Today spring arrived" },
        { uyghur: "ئۈچ كۈندىن كېيىن",               latin: "Üch kündin kéyin",                   english: "After three days" },
        { uyghur: "ئەتىگەن ئەرتە تۇرىمەن",          latin: "Etigen erte turimen",                english: "I wake up early in the morning" },
        { uyghur: "كەچ يېرىم",                        latin: "Kech yérim",                         english: "Midnight" },
        { uyghur: "ئوتتۇرا كۈن",                     latin: "Ottura kün",                         english: "Midday / Noon" },
        { uyghur: "بۇرۇن كەلگەن",                    latin: "Burun kelgen",                       english: "Came before / Earlier" },
      ]
    },
    {
      id: "weather",
      name: "Weather",
      emoji: "☀️",
      phrases: [
        { uyghur: "بۈگۈن ھاۋا قانداق؟",              latin: "Bügün hawa qandaq?",                 english: "What is the weather like today?" },
        { uyghur: "ياخشى ھاۋا",                       latin: "Yaxshi hawa",                        english: "Good weather" },
        { uyghur: "ئىسسىق ھاۋا",                      latin: "Issiq hawa",                         english: "Hot weather" },
        { uyghur: "سوغاق ھاۋا",                       latin: "Soghaq hawa",                        english: "Cold weather" },
        { uyghur: "ياغمۇر يېغىدۇ",                   latin: "Yaghmur yéghidu",                    english: "It is raining" },
        { uyghur: "قار يېغىدۇ",                       latin: "Qar yéghidu",                        english: "It is snowing" },
        { uyghur: "شامال بار",                         latin: "Shamal bar",                         english: "It is windy" },
        { uyghur: "ئاسمان بۇلۇتلۇق",                  latin: "Asman bulutluq",                     english: "The sky is cloudy" },
        { uyghur: "ئاسمان ئاچ",                       latin: "Asman ach",                          english: "The sky is clear" },
        { uyghur: "كۈن يايراپتۇ",                    latin: "Kün yayraptu",                       english: "The sun is shining" },
        { uyghur: "بۈگۈن ئىسسىق ئەمەس",              latin: "Bügün issiq emes",                   english: "It's not hot today" },
        { uyghur: "قىش كەلدى",                        latin: "Qish keldi",                         english: "Winter has come" },
        { uyghur: "ياز كەلدى",                        latin: "Yaz keldi",                          english: "Summer has come" },
        { uyghur: "كۈز پەسلى ماتۇر",                latin: "Küz pesli matur",                    english: "Autumn is beautiful" },
        { uyghur: "ھاۋا ئوزگەردى",                   latin: "Hawa özgerdi",                       english: "The weather changed" },
      ]
    },
    {
      id: "health",
      name: "Health & Medical",
      emoji: "🏥",
      phrases: [
        { uyghur: "مەن كېسەل",                        latin: "Men késel",                          english: "I am sick" },
        { uyghur: "ماڭا ياردەم كەرەك",               latin: "Manga yardem kerek",                 english: "I need help" },
        { uyghur: "دوختۇر قەيەردە؟",                 latin: "Doxtur qeyerde?",                    english: "Where is the doctor?" },
        { uyghur: "باشىم ئاغرىيدۇ",                  latin: "Bashim aghriydu",                    english: "My head aches" },
        { uyghur: "قورسىقىم ئاغرىيدۇ",              latin: "Qorsiqim aghriydu",                  english: "My stomach hurts" },
        { uyghur: "ئىسىتمام بار",                     latin: "Isitmam bar",                        english: "I have a fever" },
        { uyghur: "يۆتەل قىلىمەن",                   latin: "Yötel qilimen",                      english: "I am coughing" },
        { uyghur: "تۇماق بار",                        latin: "Tumaq bar",                          english: "I have a cold" },
        { uyghur: "دورا قايدا؟",                      latin: "Dora qayda?",                        english: "Where is the medicine?" },
        { uyghur: "داروخانا قەيەردە؟",               latin: "Daruxana qeyerde?",                  english: "Where is the pharmacy?" },
        { uyghur: "رەھمەت دوختۇر",                   latin: "Rehmet doxtur",                      english: "Thank you, doctor" },
        { uyghur: "ياخشى بولۇپ كەتتىم",              latin: "Yaxshi bolup kettim",                english: "I got better" },
        { uyghur: "كاسالخانىغا بار",                 latin: "Kasalxanigha bar",                   english: "Go to the hospital" },
        { uyghur: "ئۇيقۇ كەرەك",                     latin: "Uyqu kerek",                         english: "Need sleep" },
        { uyghur: "ساغلىق باشتىن بايلىق",           latin: "Saghliq bashtin bayliq",             english: "Health is the greatest wealth" },
      ]
    },
    {
      id: "emotions",
      name: "Emotions & Feelings",
      emoji: "💭",
      phrases: [
        { uyghur: "مەن خۇشاللىقتا",                  latin: "Men xushalliqta",                    english: "I am happy" },
        { uyghur: "مەن غەملىكمەن",                    latin: "Men ghemlikmen",                     english: "I am sad" },
        { uyghur: "مەن ئاچچىق",                       latin: "Men achiiq",                         english: "I am angry" },
        { uyghur: "مەن قورقتۇم",                      latin: "Men qorqtum",                        english: "I got scared" },
        { uyghur: "مەن چارچاق",                       latin: "Men charchiaq",                      english: "I am tired" },
        { uyghur: "بۇ ئاجايىپ!",                     latin: "Bu ajayip!",                         english: "This is amazing!" },
        { uyghur: "مەن ئۈمىد قىلىمەن",               latin: "Men ümid qilimen",                   english: "I am hopeful" },
        { uyghur: "مەن سۆيىمەن",                     latin: "Men söyimen",                        english: "I love (it/you)" },
        { uyghur: "يالغۇز ھىس قىلىمەن",              latin: "Yalghuz his qilimen",                english: "I feel lonely" },
        { uyghur: "خۇشاللىقىمدا",                    latin: "Xushalliqimda",                      english: "I am pleased / happy" },
        { uyghur: "غەمگىن بولدۇم",                   latin: "Ghemgin boldum",                     english: "I became sad" },
        { uyghur: "كۈلدۈم",                           latin: "Küldum",                             english: "I laughed" },
        { uyghur: "يىغلىدىم",                         latin: "Yighlydim",                          english: "I cried" },
        { uyghur: "مەن بەختىۋەرمەن",                  latin: "Men bextiwermen",                    english: "I am fortunate / blessed" },
        { uyghur: "ئۈمىدىم چوڭ",                     latin: "Ümidim chong",                       english: "My hope is great" },
      ]
    },
    {
      id: "school",
      name: "School & Work",
      emoji: "📚",
      phrases: [
        { uyghur: "مەن مەكتەپتە ئوقۇيمەن",           latin: "Men mektepte oquymen",               english: "I study at school" },
        { uyghur: "بۈگۈن دەرس بارمۇ؟",               latin: "Bügün ders barmu?",                  english: "Is there class today?" },
        { uyghur: "ئىمتىھان قاچان؟",                  latin: "Imtihan qachan?",                    english: "When is the exam?" },
        { uyghur: "ئوقۇتقۇچى ياخشى ئادەم",           latin: "Oqutquchi yaxshi adem",              english: "The teacher is a good person" },
        { uyghur: "مەن بۇ دەرسنى چۈشىنىمەن",        latin: "Men bu dersni chüshinimen",          english: "I understand this lesson" },
        { uyghur: "ئۆي ۋەزىپەم بار",                 latin: "Öy wezipem bar",                     english: "I have homework" },
        { uyghur: "مەن ئىشخانىدا ئىشلەيمەن",         latin: "Men ishxanida ishleymen",            english: "I work at the office" },
        { uyghur: "باشلىق كەلمىدى",                  latin: "Bashlik kelmidi",                    english: "The boss didn't come" },
        { uyghur: "ئىشتىن قايتتىم",                  latin: "Ishtin qayttim",                     english: "I returned from work" },
        { uyghur: "يىغىن قاچان؟",                    latin: "Yighin qachan?",                     english: "When is the meeting?" },
        { uyghur: "ئىش ئىزدىۋاتىمەن",               latin: "Ish izdivatimen",                    english: "I am looking for work" },
        { uyghur: "دەرسنى چۈشەنمىدىم",              latin: "Dersni chüshenmidim",                english: "I didn't understand the lesson" },
        { uyghur: "تېخىمۇ ئاستە ئېيتىڭ",            latin: "Téximu aste éyting",                 english: "Please speak more slowly" },
        { uyghur: "يەنە قايتالاڭ",                   latin: "Yne qaytaling",                      english: "Please repeat that" },
        { uyghur: "ئىلىم نور",                        latin: "Ilim nur",                           english: "Knowledge is light" },
      ]
    },
    {
      id: "culture",
      name: "Culture & Celebrations",
      emoji: "🎉",
      phrases: [
        { uyghur: "ئىد مۇبارەك!",                    latin: "Id mubarak!",                        english: "Eid Mubarak! (Happy Eid!)" },
        { uyghur: "يېڭى يىلىڭىز مۇبارەك!",           latin: "Yéngi yilingiz mubarak!",            english: "Happy New Year!" },
        { uyghur: "تۇغۇلغان كۈنۈڭىز مۇبارەك!",      latin: "Tughulghan kününgüz mubarak!",       english: "Happy Birthday!" },
        { uyghur: "ئۇيغۇر مۇسىقىسى گۈزەل",           latin: "Uyghur musiqisi güzel",              english: "Uyghur music is beautiful" },
        { uyghur: "دۇتار چالىمسىز؟",                 latin: "Dutar chalimısiz?",                  english: "Do you play the dutar?" },
        { uyghur: "مۇسىقا ياخشى كۆرىمەن",            latin: "Musiqa yaxshi körimen",              english: "I love music" },
        { uyghur: "ئۇيغۇر ئاشى ئاجايىپ",            latin: "Uyghur ashi ajayip",                 english: "Uyghur food is wonderful" },
        { uyghur: "دوپپا كىيىڭ",                     latin: "Doppa kiying",                       english: "Wear the doppa (Uyghur cap)" },
        { uyghur: "ئۇيغۇر كىيىمى چىرايلىق",         latin: "Uyghur kiyimi chiraylik",            english: "Uyghur clothing is beautiful" },
        { uyghur: "بايرام مۇبارەك!",                 latin: "Bayram mubarak!",                    english: "Happy holiday!" },
        { uyghur: "ئۇيغۇر تىلى ناھايىتى گۈزەل",    latin: "Uyghur tili nahayiti güzel",         english: "The Uyghur language is very beautiful" },
        { uyghur: "ئۇيغۇر مىراسى ئاجايىپ",          latin: "Uyghur mirasi ajayip",               english: "Uyghur heritage is wonderful" },
        { uyghur: "ئون ئىككى مۇقام",                 latin: "On ikki muqam",                      english: "The Twelve Muqam (UNESCO heritage)" },
        { uyghur: "ئۇيغۇر ئوينى ماتۇر",             latin: "Uyghur oyni matur",                  english: "Uyghur dance is beautiful" },
        { uyghur: "ئۇيغۇر تىلى مەڭگۈ ياشايدۇ!",    latin: "Uyghur tili menggü yashaidu!",       english: "The Uyghur language lives forever!" },
      ]
    },
    {
      id: "religion",
      name: "Prayers & Spirituality",
      emoji: "🕌",
      phrases: [
        { uyghur: "بىسمىللاھ",                        latin: "Bismillah",                          english: "In the name of God (before starting)" },
        { uyghur: "ئەلھەمدۈلىللاھ",                  latin: "Elhemdülillah",                      english: "Praise be to God (gratitude)" },
        { uyghur: "ئىنشاالله",                        latin: "Inshallah",                          english: "God willing / If God wills" },
        { uyghur: "ماشاالله",                         latin: "Mashaallah",                         english: "God has willed it (praise)" },
        { uyghur: "ئاللاھ ئاقلىسىن",                 latin: "Allah aqlisin",                      english: "May God forgive" },
        { uyghur: "ئاللاھ رازى بولسۇن",              latin: "Allah razi bolsun",                  english: "May God be pleased" },
        { uyghur: "نامازىم بار",                      latin: "Namazim bar",                        english: "I have prayers (time to pray)" },
        { uyghur: "مەسچىت قەيەردە؟",                 latin: "Mesjit qeyerde?",                    english: "Where is the mosque?" },
        { uyghur: "رامازان مۇبارەك",                  latin: "Ramazan mubarak",                    english: "Blessed Ramadan" },
        { uyghur: "روزىدارمەن",                       latin: "Rozidármen",                         english: "I am fasting" },
        { uyghur: "ئاللاھ ياردەم بەرسۇن",            latin: "Allah yardem bersun",                english: "May God help" },
        { uyghur: "ئاللاھقا شۈكۈر",                 latin: "Allahqa shükür",                     english: "Thanks to God" },
        { uyghur: "ئاللاھنىڭ رەھمىتى",              latin: "Allahning rehmiti",                  english: "The mercy of God" },
        { uyghur: "ئاللاھ باشىڭىزنى ساقلىسۇن",      latin: "Allah bashinghizni saqlisun",        english: "May God protect you" },
        { uyghur: "ئاللاھ كۆڭلۈڭۈزنى يۇمشاتسۇن",   latin: "Allah köngülingüzni yumshatSun",     english: "May God soften your heart" },
      ]
    },
    {
      id: "proverbs",
      name: "Proverbs & Wisdom",
      emoji: "📜",
      phrases: [
        { uyghur: "تىل بىلگەن يەردە تاپار",          latin: "Til bilgen yerde tapar",             english: "Those who know the language will find their way" },
        { uyghur: "ئىلىم نور",                        latin: "Ilim nur",                           english: "Knowledge is light" },
        { uyghur: "بىرلىك كۈچ",                      latin: "Birlik küch",                        english: "Unity is strength" },
        { uyghur: "ياخشى سۆز ياراقتىن ئۆتكۈر",      latin: "Yaxshi söz yaraqtin ötkür",         english: "Good words are sharper than weapons" },
        { uyghur: "سەۋر قىلغان ئارزۇسىغا يەتكەن",   latin: "Sewir qilghan arzusigha yetken",    english: "Those who persevere reach their desires" },
        { uyghur: "ئاق كۆڭۈللۈك بايلىق",            latin: "Aq köngüllük bayliq",               english: "Sincerity is wealth" },
        { uyghur: "ئادەم ئادەمگە تاياق",             latin: "Adem ademge tayaq",                  english: "People are a support for each other" },
        { uyghur: "يېشىلىكتە ئۆگەن",                 latin: "Yéshilikté ögen",                    english: "Learn while young" },
        { uyghur: "سابىر قىلغان زەپەر تاپار",        latin: "Sabir qilghan zefer tapar",         english: "The patient one finds victory" },
        { uyghur: "بىر كۈنلۈك ئىشنى ئەتەگە قويما",  latin: "Bir künlük ishni etege qoyma",      english: "Don't leave today's work for tomorrow" },
        { uyghur: "ئاكا-ئىنى ئۇچراشمىسىدا ئالتۇن",  latin: "Aka-ini uchrashmisida altun",        english: "Brothers' gathering is gold" },
        { uyghur: "ئات ياخشى يول يۈرۈر",             latin: "At yaxshi yol yürür",               english: "A good horse walks a good road" },
        { uyghur: "ئاش بىلەن دوست ئاچتى",           latin: "Ash bilen dost achti",               english: "Opened friendship with food" },
        { uyghur: "ساغلىق باشتىن بايلىق",           latin: "Saghliq bashtin bayliq",             english: "Health is the greatest wealth" },
        { uyghur: "ئۇيغۇر تىلى مەڭگۈ ياشايدۇ",     latin: "Uyghur tili menggü yashaidu",        english: "The Uyghur language lives forever" },
      ]
    },
  ],

  levels: [
    { level: 0, name: "Beginner",           uyghur: "يېڭى ئۆگەنگۈچى",  emoji: "🌱", wordsNeeded: 0,   color: "#10B981", desc: "Starting your Uyghur journey" },
    { level: 1, name: "Elementary",         uyghur: "ئاساسىي",           emoji: "📗", wordsNeeded: 100, color: "#3B82F6", desc: "Building the basics" },
    { level: 2, name: "Pre-Intermediate",   uyghur: "ئوتتۇرى ئاستى",    emoji: "📘", wordsNeeded: 200, color: "#06B6D4", desc: "Growing confidence" },
    { level: 3, name: "Intermediate",       uyghur: "ئوتتۇرا",           emoji: "⭐", wordsNeeded: 300, color: "#F59E0B", desc: "Conversational level" },
    { level: 4, name: "Upper-Intermediate", uyghur: "ئوتتۇرى ئۈستى",    emoji: "🌟", wordsNeeded: 400, color: "#F97316", desc: "Complex discussions" },
    { level: 5, name: "Advanced",           uyghur: "ئىلغار",            emoji: "🏆", wordsNeeded: 500, color: "#8B5CF6", desc: "Advanced conversations" },
    { level: 6, name: "Upper-Advanced",     uyghur: "ئالىي ئىلغار",     emoji: "💎", wordsNeeded: 600, color: "#EC4899", desc: "Near-native ability" },
    { level: 7, name: "Expert",             uyghur: "مۇتەخەسسىس",       emoji: "🎓", wordsNeeded: 700, color: "#EF4444", desc: "Expert command" },
    { level: 8, name: "Master",             uyghur: "ئۇستاز",            emoji: "👑", wordsNeeded: 800, color: "#DC2626", desc: "Master of Uyghur" },
    { level: 9, name: "Fluent",             uyghur: "سۇيۇق سۆزلىگۈچى", emoji: "🦅", wordsNeeded: 900, color: "#7C3AED", desc: "Fluent in Uyghur!" },
  ]
};
